export const FINTECH_CONTENT = {
  brand: {
    tagline: "Precision GTM for the Future of Finance.",
    description: "GTMStack.pro empowers FinTech innovators to navigate complex markets, accelerate adoption, and achieve compliant, sustainable growth with unparalleled strategic clarity."
  },
  hero: {
    headline: "Master FinTech Market Entry and Scale with Unrivaled Precision.",
    subheadline: "Transform regulatory challenges into strategic advantages and capture market share faster than ever before.",
    description: "In the rapidly evolving FinTech landscape, speed, security, and compliance are paramount. GTMStack.pro provides the specialized Go-To-Market framework and intelligence needed to launch, grow, and dominate, ensuring every strategy is robust, scalable, and fully compliant.",
    primaryCTA: { label: "Get in Touch", href: "/contact" },
    secondaryCTA: { label: "Explore FinTech Solutions", href: "/solutions/fintech" },
    image: { src: "/images/fintech-hero.webp", alt: "Abstract representation of secure financial data flow and market growth" }
  },
  metricsSection: {
    headline: "Quantifiable Impact in a High-Stakes Industry.",
    stats: [
      { value: "30%+", label: "Faster Market Entry", description: "Clients achieve market readiness and launch significantly quicker, outpacing competitors." },
      { value: "99.9%", label: "Compliance Adherence", description: "Ensuring robust regulatory frameworks are integrated into every GTM strategy." },
      { value: "$1.2B+", label: "Client Revenue Growth", description: "Total incremental revenue generated by FinTech clients leveraging our strategies." }
    ]
  },
  capabilitiesSection: {
    headline: "Specialized GTM Capabilities for FinTech Excellence.",
    items: [
      { icon: "target", title: "Regulatory Compliance Mapping", description: "Navigate global financial regulations with precision, integrating compliance directly into your GTM strategy from day one." },
      { icon: "target", title: "Secure Customer Onboarding Flows", description: "Design and implement frictionless, secure, and compliant onboarding journeys that build trust and reduce churn." },
      { icon: "target", title: "Data-Driven Market Expansion", description: "Leverage advanced analytics to identify high-potential markets and tailor expansion strategies for optimal penetration and ROI." },
      { icon: "target", title: "FinTech Product Launch Optimization", description: "From concept to market, optimize every phase of your product launch for maximum impact, adoption, and sustained growth." },
      { icon: "target", title: "Competitive Intelligence & Positioning", description: "Gain a decisive edge with deep insights into competitor strategies and craft unique value propositions that resonate with your target audience." }
    ]
  },
  philosophySection: {
    headline: "Our Principles: Building Trust and Driving Innovation in FinTech.",
    principles: [
      { title: "Compliance as a Cornerstone", description: "We believe that robust regulatory adherence is not a barrier, but a fundamental enabler of sustainable FinTech growth and market trust." },
      { title: "Security by Design", description: "Every GTM strategy is architected with data security and privacy at its core, protecting both your business and your customers." },
      { title: "Data-Driven Agility", description: "In a dynamic industry, our strategies are built on real-time data and designed for rapid iteration, ensuring continuous optimization and responsiveness." },
      { title: "Strategic Partnership", description: "We act as an extension of your team, providing expert guidance and hands-on support to navigate the unique complexities of the FinTech landscape." }
    ]
  },
  growthSection: {
    headline: "Transforming FinTech Ambition into Market Leadership.",
    narrative: "The FinTech sector demands more than just innovation; it requires a GTM strategy that is both visionary and meticulously executed. GTMStack.pro partners with leading FinTech companies to overcome market fragmentation, regulatory hurdles, and intense competition. We empower you to not only launch groundbreaking products but to establish enduring market presence, cultivate deep customer loyalty, and achieve exponential growth that redefines industry standards.",
    metrics: [
      { label: "Market Share Growth", value: "15% Average", description: "Clients consistently expand their market share within their target segments." },
      { label: "Customer Lifetime Value", value: "2.5x Increase", description: "Optimized GTM strategies lead to significantly higher customer retention and value." },
      { label: "Operational Efficiency", value: "20% Reduction in CAC", description: "Streamlined processes and targeted campaigns reduce customer acquisition costs." }
    ]
  },
  ctaSection: {
    title: "Ready to Redefine Your FinTech Growth Trajectory?",
    subtitle: "Partner with GTMStack.pro to build a compliant, secure, and high-impact Go-To-Market strategy that delivers measurable results.",
    button: { label: "Get in Touch", href: "/contact" }
  },
  footer: {
    description: "GTMStack.pro is the trusted partner for FinTech companies seeking to achieve compliant, secure, and accelerated market growth through expert Go-To-Market strategies.",
    sections: [
      { title: "Solutions", links: [{ label: "FinTech GTM", href: "/solutions/fintech" }, { label: "Market Entry", href: "/solutions/market-entry" }, { label: "Growth Optimization", href: "/solutions/growth-optimization" }] },
      { title: "Company", links: [{ label: "About Us", href: "/about" }, { label: "Careers", href: "/careers" }, { label: "Contact", href: "/contact" }] },
      { title: "Resources", links: [{ label: "Blog", href: "/blog" }, { label: "Case Studies", href: "/case-studies" }, { label: "Whitepapers", href: "/whitepapers" }] },
      { title: "Legal", links: [{ label: "Privacy Policy", href: "/privacy" }, { label: "Terms of Service", href: "/terms" }] }
    ],
    copyright: "© 2026 GTMStack.pro. All rights reserved."
  }
}