/**
 * Build-time generator: reads src/data/page-registry.csv and emits
 * src/data/pageRegistry.generated.ts. Run via: npm run gen:registry
 */
import fs from 'node:fs'
import path from 'node:path'

const ROOT = process.cwd()
const CSV_PATH = path.join(ROOT, 'src', 'data', 'page-registry.csv')
const OUT_PATH = path.join(ROOT, 'src', 'data', 'pageRegistry.generated.ts')

const REQUIRED_FIELDS = ['route', 'fileRef', 'pageTitle', 'templateId', 'contentKey'] as const
const TEMPLATE_IDS = ['expertise.category', 'expertise.topic', 'expertise.main', 'gallery.main', 'industry.base', 'industries.main', 'projects.main', 'caseStudy.base', 'home.base', 'home.main'] as const
const THEMES = ['dark', 'light'] as const

function parseCsvRow(line: string): string[] {
  const out: string[] = []
  let cur = ''
  let inQuotes = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i]
    if (c === '"') {
      inQuotes = !inQuotes
    } else if (inQuotes) {
      cur += c
    } else if (c === ',') {
      out.push(cur.trim())
      cur = ''
    } else {
      cur += c
    }
  }
  out.push(cur.trim())
  return out
}

function normalizeRoute(route: string): string {
  if (route === '/') return '/'
  return route.replace(/\/+$/, '') || '/'
}

function main(): void {
  const raw = fs.readFileSync(CSV_PATH, 'utf8')
  const lines = raw.split(/\r?\n/).map((l) => l.trim()).filter(Boolean)
  if (lines.length < 2) {
    throw new Error(`${CSV_PATH}: need at least header + one data row`)
  }

  const header = parseCsvRow(lines[0])
  const requiredSet = new Set(REQUIRED_FIELDS)
  for (const f of REQUIRED_FIELDS) {
    if (!header.includes(f)) {
      throw new Error(`${CSV_PATH}: missing required column "${f}". Header: ${header.join(',')}`)
    }
  }

  const rows: Record<string, string>[] = []
  for (let i = 1; i < lines.length; i++) {
    const values = parseCsvRow(lines[i])
    const row: Record<string, string> = {}
    for (let j = 0; j < header.length; j++) {
      row[header[j]] = values[j] ?? ''
    }

    for (const f of REQUIRED_FIELDS) {
      const v = (row[f] ?? '').trim()
      if (!v) {
        throw new Error(`${CSV_PATH}: row ${i + 1}: missing required field "${f}"`)
      }
    }

    const templateId = row.templateId!.trim()
    // No longer strictly validating against TEMPLATE_IDS to allow free-form uploaded templates
    /*
    if (!(TEMPLATE_IDS as readonly string[]).includes(templateId)) {
      throw new Error(
        `${CSV_PATH}: row ${i + 1}: templateId must be one of ${TEMPLATE_IDS.join(', ')}; got "${templateId}"`
      )
    }
    */

    const themeRaw = (row.theme ?? '').trim()
    if (themeRaw && !(THEMES as readonly string[]).includes(themeRaw)) {
      throw new Error(
        `${CSV_PATH}: row ${i + 1}: theme must be empty or one of ${THEMES.join(', ')}; got "${themeRaw}"`
      )
    }

    row.route = normalizeRoute(row.route!.trim())
    row.theme = themeRaw
    rows.push(row)
  }

  function rowToTsLiteral(r: Record<string, string>): string {
    const themeVal = r.theme ? `'${r.theme}'` : 'undefined'
    return `{ route: ${JSON.stringify(r.route)}, fileRef: ${JSON.stringify(r.fileRef)}, pageTitle: ${JSON.stringify(r.pageTitle)}, templateId: '${r.templateId}', contentKey: ${JSON.stringify(r.contentKey)}, theme: ${themeVal}, heroVisualId: ${JSON.stringify(r.heroVisualId ?? '')} }`
  }

  const rowsArr = '[\n' + rows.map((r) => '  ' + rowToTsLiteral(r)).join(',\n') + '\n]'
  // Dedupe by route: last row wins (object literal cannot have duplicate keys)
  const byRoute = new Map<string, Record<string, string>>()
  for (const r of rows) {
    byRoute.set(r.route, r)
  }
  const pageByRouteEntries = Array.from(byRoute.entries())
    .map(([route, r]) => `  ${JSON.stringify(route)}: ${rowToTsLiteral(r)}`)
    .join(',\n')

  const templateIdUnion = TEMPLATE_IDS.map((id) => `  | '${id}'`).join('\n')
  const ts = `// Generated by scripts/gen-page-registry.ts — do not edit manually.
// Source of truth: src/data/page-registry.csv

// TemplateId union from legacy IDs; custom uploaded templates are free-form strings.
export type TemplateId =
${templateIdUnion}
  | (string & {})

export type Theme = 'dark' | 'light' | undefined

export interface PageRegistryRow {
  route: string
  fileRef: string
  pageTitle: string
  templateId: TemplateId
  contentKey: string
  theme: Theme
  heroVisualId: string
}

export const PAGE_REGISTRY: PageRegistryRow[] = ${rowsArr}

export const PAGE_BY_ROUTE: Record<string, PageRegistryRow> = {
${pageByRouteEntries}
}
`

  fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true })
  fs.writeFileSync(OUT_PATH, ts, 'utf8')
  console.log('Wrote:', OUT_PATH, `(${rows.length} rows)`)
}

main()
