// Auto-generated index file for all expertise content
// Importing all expertise content with unique aliases to avoid naming conflicts

import { ACCOUNT_BASED_MARKETING_ABM_CONTENT } from './account-based-marketing-abm';
import { ACCOUNT_BASED_MARKETING_CONTENT } from './account-based-marketing';
import { REPORTING_DASHBOARDS_ATTRIBUTION_CONTENT as ANALYTICS_CONTENT } from './analytics';
import { COMPETITIVE_INTELLIGENCE_POSITIONING_CONTENT } from './competitive-intel';
import { CONTENT_ENGAGEMENT_CONTENT } from './content-engagement';
import { CONTENT_MARKETING_PERSONALIZATION_CONTENT } from './content-marketing';
import { CRM_MANAGEMENT_CONTENT } from './crm-management';
import { GTMSTACK_PRO_CONTENT as CUSTOMER_MARKETING_CONTENT } from './customer-marketing';
import { CYBERSECURITY_CONTENT } from './cybersecurity';
import { DEMAND_GENERATION_CONTENT } from './demand-generation';
import { EXPERTISE_CONTENT as DEMAND_GROWTH_CONTENT } from './demand-growth';
import { DEVELOPER_TOOLS_CONTENT } from './developer-tools';
import { EXPERTISE_CONTENT as ENERGY_UTILITIES_CONTENT } from './energy-utilities';
import { EVENT_MARKETING_CONTENT } from './event-marketing';
import { MARKETING_CONTENT as EXPERTISE_MARKETING_CONTENT } from './expertise';
import { FINANCIAL_SERVICES_CONTENT } from './financial-services';
import { FLEET_MANAGEMENT_LOGISTICS_CONTENT } from './fleet-management-logistics';
import { GTMSTACK_PRO_EXPERTISE_CONTENT as HEALTHCARE_CONTENT } from './healthcare';
import { LEAD_GEN_SCORING_CONTENT } from './lead-gen-scoring';
import { EXPERTISE_MAIN_CONTENT } from './main';
import { EXPERTISE_CONTENT as MANUFACTURING_CONTENT } from './manufacturing';
import { REPORTING_DASHBOARDS_ATTRIBUTION_CONTENT as MARKETING_ANALYTICS_REPORTING_CONTENT } from './marketing-analytics-reporting';
import { MARKETING_AUTOMATION_CONTENT } from './marketing-automation';
import { MARTECH_OPTIMIZATION_CONTENT } from './martech-optimization';
import { EXPERTISE_CONTENT as NON_PROFIT_EDUCATION_CONTENT } from './non-profit-education';
import { PAID_ADVERTISING_SEM_CONTENT } from './paid-advertising-sem';
import { EXPERTISE_CONTENT as PRODUCT_MARKETING_CONTENT } from './product-marketing';
import { PUBLIC_SECTOR_GOVERNMENT_CONTENT } from './pubsec-government';
import { GTM_STRATEGY_CONTENT as RETAIL_CONTENT } from './retail';
import { EXPERTISE_CONTENT as ROI_ANALYSIS_CONTENT } from './roi-analysis';
import { EXPERTISE_CONTENT as ROUTE_CONTENT } from './Route';
import { EXPERTISE_CONTENT as SALES_ENABLEMENT_CONTENT } from './sales-enablement';
import { SEARCH_ENGINE_OPTIMIZATION_CONTENT } from './search-engine-optimization';
import { GO_TO_MARKET_STRATEGY_CONTENT as SOCIAL_MEDIA_MARKETING_CONTENT } from './social-media-marketing';
import { EXPERTISE_CONTENT as STRATEGY_INSIGHTS_CONTENT } from './strategy-insights';
import { EXPERTISE_CONTENT as STRATEGY_CONTENT } from './strategy';
import { SUPPLY_CHAIN_LOGISTICS_CONTENT } from './supply-chain-logistics';
import { GTM_SYSTEMS_OPERATIONS_CONTENT } from './systems-operations';
import { GTMSTACK_PRO_CONTENT as TECHNOLOGY_SAAS_CONTENT } from './technology-saas';
import { EXPERTISE_CONTENT as WEB_DESIGN_UI_UX_CONTENT } from './web-design-ui-ux';

// Re-export all individual content objects
export {
  ACCOUNT_BASED_MARKETING_ABM_CONTENT,
  ACCOUNT_BASED_MARKETING_CONTENT,
  ANALYTICS_CONTENT,
  COMPETITIVE_INTELLIGENCE_POSITIONING_CONTENT,
  CONTENT_ENGAGEMENT_CONTENT,
  CONTENT_MARKETING_PERSONALIZATION_CONTENT,
  CRM_MANAGEMENT_CONTENT,
  CUSTOMER_MARKETING_CONTENT,
  CYBERSECURITY_CONTENT,
  DEMAND_GENERATION_CONTENT,
  DEMAND_GROWTH_CONTENT,
  DEVELOPER_TOOLS_CONTENT,
  ENERGY_UTILITIES_CONTENT,
  EVENT_MARKETING_CONTENT,
  EXPERTISE_MARKETING_CONTENT,
  FINANCIAL_SERVICES_CONTENT,
  FLEET_MANAGEMENT_LOGISTICS_CONTENT,
  HEALTHCARE_CONTENT,
  LEAD_GEN_SCORING_CONTENT,
  EXPERTISE_MAIN_CONTENT,
  MANUFACTURING_CONTENT,
  MARKETING_ANALYTICS_REPORTING_CONTENT,
  MARKETING_AUTOMATION_CONTENT,
  MARTECH_OPTIMIZATION_CONTENT,
  NON_PROFIT_EDUCATION_CONTENT,
  PAID_ADVERTISING_SEM_CONTENT,
  PRODUCT_MARKETING_CONTENT,
  PUBLIC_SECTOR_GOVERNMENT_CONTENT,
  RETAIL_CONTENT,
  ROI_ANALYSIS_CONTENT,
  ROUTE_CONTENT,
  SALES_ENABLEMENT_CONTENT,
  SEARCH_ENGINE_OPTIMIZATION_CONTENT,
  SOCIAL_MEDIA_MARKETING_CONTENT,
  STRATEGY_INSIGHTS_CONTENT,
  STRATEGY_CONTENT,
  SUPPLY_CHAIN_LOGISTICS_CONTENT,
  GTM_SYSTEMS_OPERATIONS_CONTENT,
  TECHNOLOGY_SAAS_CONTENT,
  WEB_DESIGN_UI_UX_CONTENT,
};

// Export all expertise content as a single array for easy iteration
export const allExpertiseContent = [
  ACCOUNT_BASED_MARKETING_ABM_CONTENT,
  ACCOUNT_BASED_MARKETING_CONTENT,
  ANALYTICS_CONTENT,
  COMPETITIVE_INTELLIGENCE_POSITIONING_CONTENT,
  CONTENT_ENGAGEMENT_CONTENT,
  CONTENT_MARKETING_PERSONALIZATION_CONTENT,
  CRM_MANAGEMENT_CONTENT,
  CUSTOMER_MARKETING_CONTENT,
  CYBERSECURITY_CONTENT,
  DEMAND_GENERATION_CONTENT,
  DEMAND_GROWTH_CONTENT,
  DEVELOPER_TOOLS_CONTENT,
  ENERGY_UTILITIES_CONTENT,
  EVENT_MARKETING_CONTENT,
  EXPERTISE_MARKETING_CONTENT,
  FINANCIAL_SERVICES_CONTENT,
  FLEET_MANAGEMENT_LOGISTICS_CONTENT,
  HEALTHCARE_CONTENT,
  LEAD_GEN_SCORING_CONTENT,
  EXPERTISE_MAIN_CONTENT,
  MANUFACTURING_CONTENT,
  MARKETING_ANALYTICS_REPORTING_CONTENT,
  MARKETING_AUTOMATION_CONTENT,
  MARTECH_OPTIMIZATION_CONTENT,
  NON_PROFIT_EDUCATION_CONTENT,
  PAID_ADVERTISING_SEM_CONTENT,
  PRODUCT_MARKETING_CONTENT,
  PUBLIC_SECTOR_GOVERNMENT_CONTENT,
  RETAIL_CONTENT,
  ROI_ANALYSIS_CONTENT,
  ROUTE_CONTENT,
  SALES_ENABLEMENT_CONTENT,
  SEARCH_ENGINE_OPTIMIZATION_CONTENT,
  SOCIAL_MEDIA_MARKETING_CONTENT,
  STRATEGY_INSIGHTS_CONTENT,
  STRATEGY_CONTENT,
  SUPPLY_CHAIN_LOGISTICS_CONTENT,
  GTM_SYSTEMS_OPERATIONS_CONTENT,
  TECHNOLOGY_SAAS_CONTENT,
  WEB_DESIGN_UI_UX_CONTENT,
] as const;
