// Generated by scripts/gen-animation-catalog.ts — do not edit manually.
// Source of truth: src/components/animations/*.tsx

export type AnimationCatalogItem = {
  id: string
  title: string
  componentPath: string
  thumbnailSrc: string
  repoUrl?: string
  usedOnPages: boolean
}

export const ANIMATION_CATALOG: AnimationCatalogItem[] = [
  {
    id: "a-b-m-pipe-tracker-tile",
    title: "A B M Pipe Tracker Tile",
    componentPath: "@/components/animations/ABMPipeTrackerTile",
    thumbnailSrc: "/images/gallery-thumbnails/ABMPipeTrackerTile.png",

    usedOnPages: false,
  },
  {
    id: "a-b-m-tile-animation",
    title: "A B M Tile Animation",
    componentPath: "@/components/animations/ABMTileAnimation",
    thumbnailSrc: "/images/gallery-thumbnails/ABMTileAnimation.png",

    usedOnPages: false,
  },
  {
    id: "a-b-m90-days",
    title: "A B M90 Days",
    componentPath: "@/components/animations/ABM90Days",
    thumbnailSrc: "/images/gallery-thumbnails/ABM90Days.png",

    usedOnPages: false,
  },
  {
    id: "a-i-growth",
    title: "A I Growth",
    componentPath: "@/components/animations/AIGrowth",
    thumbnailSrc: "/images/gallery-thumbnails/AIGrowth.png",

    usedOnPages: false,
  },
  {
    id: "abm-network-dashboard",
    title: "Abm Network Dashboard",
    componentPath: "@/components/animations/abm-network-dashboard",
    thumbnailSrc: "/images/gallery-thumbnails/abm-network-dashboard.png",

    usedOnPages: false,
  },
  {
    id: "a-b-m-pipeline-strategy",
    title: "ABM Pipeline Strategy",
    componentPath: "@/components/animations/ABM-Pipeline-Strategy",
    thumbnailSrc: "/images/gallery-thumbnails/ABM-Pipeline-Strategy.png",

    usedOnPages: false,
  },
  {
    id: "a-b-m-radar-analysis",
    title: "ABM Radar Analysis",
    componentPath: "@/components/animations/ABM-Radar-Analysis",
    thumbnailSrc: "/images/gallery-thumbnails/ABM-Radar-Analysis.png",

    usedOnPages: false,
  },
  {
    id: "airplane",
    title: "Airplane",
    componentPath: "@/components/animations/Airplane",
    thumbnailSrc: "/images/gallery-thumbnails/Airplane.png",

    usedOnPages: false,
  },
  {
    id: "apex-shield-lifecycle-engine",
    title: "Apex Shield Lifecycle Engine",
    componentPath: "@/components/animations/ApexShieldLifecycleEngine",
    thumbnailSrc: "/images/gallery-thumbnails/ApexShieldLifecycleEngine.png",

    usedOnPages: false,
  },
  {
    id: "automation-engine-dashboard",
    title: "Automation Engine Dashboard",
    componentPath: "@/components/animations/automation-engine-dashboard",
    thumbnailSrc: "/images/gallery-thumbnails/automation-engine-dashboard.png",

    usedOnPages: false,
  },
  {
    id: "background-grid",
    title: "Background Grid",
    componentPath: "@/components/animations/BackgroundGrid",
    thumbnailSrc: "/images/gallery-thumbnails/BackgroundGrid.png",

    usedOnPages: false,
  },
  {
    id: "c-r-m-campaigns-tile",
    title: "C R M Campaigns Tile",
    componentPath: "@/components/animations/CRMCampaignsTile",
    thumbnailSrc: "/images/gallery-thumbnails/CRMCampaignsTile.png",

    usedOnPages: false,
  },
  {
    id: "campaign-tile",
    title: "Campaign Tile",
    componentPath: "@/components/animations/CampaignTile",
    thumbnailSrc: "/images/gallery-thumbnails/CampaignTile.png",

    usedOnPages: false,
  },
  {
    id: "clinical-holographic-control-surface",
    title: "Clinical Holographic Control Surface",
    componentPath: "@/components/animations/ClinicalHolographicControlSurface",
    thumbnailSrc: "/images/gallery-thumbnails/ClinicalHolographicControlSurface.png",

    usedOnPages: false,
  },
  {
    id: "content-engagement-marketing",
    title: "Content Engagement Marketing",
    componentPath: "@/components/animations/Content-Engagement-Marketing",
    thumbnailSrc: "/images/gallery-thumbnails/Content-Engagement-Marketing.png",

    usedOnPages: false,
  },
  {
    id: "content-engagement-tile",
    title: "Content Engagement Tile",
    componentPath: "@/components/animations/ContentEngagementTile",
    thumbnailSrc: "/images/gallery-thumbnails/ContentEngagementTile.png",

    usedOnPages: false,
  },
  {
    id: "content-marketing",
    title: "Content Marketing",
    componentPath: "@/components/animations/Content-Marketing",
    thumbnailSrc: "/images/gallery-thumbnails/Content-Marketing.png",

    usedOnPages: false,
  },
  {
    id: "content-marketing",
    title: "Content Marketing",
    componentPath: "@/components/animations/ContentMarketing",
    thumbnailSrc: "/images/gallery-thumbnails/ContentMarketing.png",

    usedOnPages: false,
  },
  {
    id: "content-marketing-animation",
    title: "Content Marketing Animation",
    componentPath: "@/components/animations/ContentMarketingAnimation",
    thumbnailSrc: "/images/gallery-thumbnails/ContentMarketingAnimation.png",

    usedOnPages: false,
  },
  {
    id: "content-marketing-hero",
    title: "Content Marketing Hero",
    componentPath: "@/components/animations/ContentMarketingHero",
    thumbnailSrc: "/images/gallery-thumbnails/ContentMarketingHero.png",

    usedOnPages: false,
  },
  {
    id: "content-strategist-dashboard",
    title: "Content Strategist Dashboard",
    componentPath: "@/components/animations/ContentStrategistDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/ContentStrategistDashboard.png",

    usedOnPages: false,
  },
  {
    id: "demand-gen-flow",
    title: "Demand Gen Flow",
    componentPath: "@/components/animations/DemandGenFlow",
    thumbnailSrc: "/images/gallery-thumbnails/DemandGenFlow.png",

    usedOnPages: false,
  },
  {
    id: "demand-generation-hero",
    title: "Demand Generation Hero",
    componentPath: "@/components/animations/DemandGenerationHero",
    thumbnailSrc: "/images/gallery-thumbnails/DemandGenerationHero.png",

    usedOnPages: false,
  },
  {
    id: "demand-generation-hero-tile",
    title: "Demand Generation Hero Tile",
    componentPath: "@/components/animations/DemandGenerationHeroTile",
    thumbnailSrc: "/images/gallery-thumbnails/DemandGenerationHeroTile.png",

    usedOnPages: false,
  },
  {
    id: "demand-growth-tile",
    title: "Demand Growth Tile",
    componentPath: "@/components/animations/DemandGrowthTile",
    thumbnailSrc: "/images/gallery-thumbnails/DemandGrowthTile.png",

    usedOnPages: false,
  },
  {
    id: "dev-marketers",
    title: "Dev Marketers",
    componentPath: "@/components/animations/DevMarketers",
    thumbnailSrc: "/images/gallery-thumbnails/DevMarketers.png",

    usedOnPages: false,
  },
  {
    id: "developer-marketing",
    title: "Developer Marketing",
    componentPath: "@/components/animations/Developer-Marketing",
    thumbnailSrc: "/images/gallery-thumbnails/Developer-Marketing.png",

    usedOnPages: false,
  },
  {
    id: "drift-guard",
    title: "Drift Guard",
    componentPath: "@/components/animations/DriftGuard",
    thumbnailSrc: "/images/gallery-thumbnails/DriftGuard.png",

    usedOnPages: false,
  },
  {
    id: "e-d-u-marketing-tile",
    title: "E D U Marketing Tile",
    componentPath: "@/components/animations/EDUMarketingTile",
    thumbnailSrc: "/images/gallery-thumbnails/EDUMarketingTile.png",

    usedOnPages: false,
  },
  {
    id: "ed-journey-k12-ecosystem",
    title: "Ed Journey K12 Ecosystem",
    componentPath: "@/components/animations/EdJourneyK12Ecosystem",
    thumbnailSrc: "/images/gallery-thumbnails/EdJourneyK12Ecosystem.png",

    usedOnPages: false,
  },
  {
    id: "ed-tech-compact-r-o-i-funnel",
    title: "Ed Tech Compact R O I Funnel",
    componentPath: "@/components/animations/EdTechCompactROIFunnel",
    thumbnailSrc: "/images/gallery-thumbnails/EdTechCompactROIFunnel.png",

    usedOnPages: false,
  },
  {
    id: "ed-tech-r-o-i-funnel",
    title: "Edtech ROI Funnel",
    componentPath: "@/components/animations/EdTech-ROI-Funnel",
    thumbnailSrc: "/images/gallery-thumbnails/EdTech-ROI-Funnel.png",

    usedOnPages: false,
  },
  {
    id: "edu-marketers-dashboard",
    title: "Edu Marketers Dashboard",
    componentPath: "@/components/animations/EduMarketersDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/EduMarketersDashboard.png",

    usedOnPages: false,
  },
  {
    id: "email-automation-component",
    title: "Email Automation Component",
    componentPath: "@/components/animations/EmailAutomationComponent",
    thumbnailSrc: "/images/gallery-thumbnails/EmailAutomationComponent.png",

    usedOnPages: false,
  },
  {
    id: "email-marketing-hero",
    title: "Email Marketing Hero",
    componentPath: "@/components/animations/EmailMarketingHero",
    thumbnailSrc: "/images/gallery-thumbnails/EmailMarketingHero.png",

    usedOnPages: false,
  },
  {
    id: "energy-flow-digital",
    title: "Energy Flow Digital",
    componentPath: "@/components/animations/EnergyFlowDigital",
    thumbnailSrc: "/images/gallery-thumbnails/EnergyFlowDigital.png",

    usedOnPages: false,
  },
  {
    id: "energy-grid-tile",
    title: "Energy Grid Tile",
    componentPath: "@/components/animations/EnergyGridTile",
    thumbnailSrc: "/images/gallery-thumbnails/EnergyGridTile.png",

    usedOnPages: false,
  },
  {
    id: "engineering-excellence-workflow-tile",
    title: "Engineering Excellence Workflow Tile",
    componentPath: "@/components/animations/EngineeringExcellenceWorkflowTile",
    thumbnailSrc: "/images/gallery-thumbnails/EngineeringExcellenceWorkflowTile.png",

    usedOnPages: false,
  },
  {
    id: "engineering-workflow",
    title: "Engineering Workflow",
    componentPath: "@/components/animations/EngineeringWorkflow",
    thumbnailSrc: "/images/gallery-thumbnails/EngineeringWorkflow.png",

    usedOnPages: false,
  },
  {
    id: "engineering-workflow-system",
    title: "Engineering Workflow System",
    componentPath: "@/components/animations/EngineeringWorkflowSystem",
    thumbnailSrc: "/images/gallery-thumbnails/EngineeringWorkflowSystem.png",

    usedOnPages: false,
  },
  {
    id: "enterprise-sales-motion-dashboard",
    title: "Enterprise Sales Motion Dashboard",
    componentPath: "@/components/animations/EnterpriseSalesMotionDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/EnterpriseSalesMotionDashboard.png",

    usedOnPages: false,
  },
  {
    id: "eoc-logistics-dashboard",
    title: "Eoc Logistics Dashboard",
    componentPath: "@/components/animations/EocLogisticsDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/EocLogisticsDashboard.png",

    usedOnPages: false,
  },
  {
    id: "esg-analytics-hub",
    title: "Esg Analytics Hub",
    componentPath: "@/components/animations/EsgAnalyticsHub",
    thumbnailSrc: "/images/gallery-thumbnails/EsgAnalyticsHub.png",

    usedOnPages: false,
  },
  {
    id: "event-marketing",
    title: "Event Marketing",
    componentPath: "@/components/animations/EventMarketing",
    thumbnailSrc: "/images/gallery-thumbnails/EventMarketing.png",

    usedOnPages: false,
  },
  {
    id: "event-marketing-tile",
    title: "Event Marketing Tile",
    componentPath: "@/components/animations/EventMarketingTile",
    thumbnailSrc: "/images/gallery-thumbnails/EventMarketingTile.png",

    usedOnPages: false,
  },
  {
    id: "event-pulse",
    title: "Event Pulse",
    componentPath: "@/components/animations/EventPulse",
    thumbnailSrc: "/images/gallery-thumbnails/EventPulse.png",

    usedOnPages: false,
  },
  {
    id: "executive-logistics-dashboard",
    title: "Executive Logistics Dashboard",
    componentPath: "@/components/animations/ExecutiveLogisticsDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/ExecutiveLogisticsDashboard.png",

    usedOnPages: false,
  },
  {
    id: "financial-tile",
    title: "Financial Tile",
    componentPath: "@/components/animations/FinancialTile",
    thumbnailSrc: "/images/gallery-thumbnails/FinancialTile.png",

    usedOnPages: false,
  },
  {
    id: "fleet-r-o-i-calculator",
    title: "Fleet R O I Calculator",
    componentPath: "@/components/animations/FleetROICalculator",
    thumbnailSrc: "/images/gallery-thumbnails/FleetROICalculator.png",

    usedOnPages: false,
  },
  {
    id: "fleet-tile",
    title: "Fleet Tile",
    componentPath: "@/components/animations/FleetTile",
    thumbnailSrc: "/images/gallery-thumbnails/FleetTile.png",

    usedOnPages: false,
  },
  {
    id: "g-t-m-audience-tile",
    title: "G T M Audience Tile",
    componentPath: "@/components/animations/GTMAudienceTile",
    thumbnailSrc: "/images/gallery-thumbnails/GTMAudienceTile.png",

    usedOnPages: false,
  },
  {
    id: "g-t-m-audience-tile-hero",
    title: "G T M Audience Tile Hero",
    componentPath: "@/components/animations/GTMAudienceTileHero",
    thumbnailSrc: "/images/gallery-thumbnails/GTMAudienceTileHero.png",

    usedOnPages: false,
  },
  {
    id: "g-t-m-stack-hero",
    title: "G T M Stack Hero",
    componentPath: "@/components/animations/GTMStackHero",
    thumbnailSrc: "/images/gallery-thumbnails/GTMStackHero.png",

    usedOnPages: false,
  },
  {
    id: "g-t-m-stack-pro",
    title: "G T M Stack Pro",
    componentPath: "@/components/animations/GTMStackPro",
    thumbnailSrc: "/images/gallery-thumbnails/GTMStackPro.png",

    usedOnPages: false,
  },
  {
    id: "growth-marketing-hero",
    title: "Growth Marketing Hero",
    componentPath: "@/components/animations/GrowthMarketingHero",
    thumbnailSrc: "/images/gallery-thumbnails/GrowthMarketingHero.png",

    usedOnPages: false,
  },
  {
    id: "growth-marketing-tile",
    title: "Growth Marketing Tile",
    componentPath: "@/components/animations/GrowthMarketingTile",
    thumbnailSrc: "/images/gallery-thumbnails/GrowthMarketingTile.png",

    usedOnPages: false,
  },
  {
    id: "growth-s-e-m-tile",
    title: "Growth S E M Tile",
    componentPath: "@/components/animations/GrowthSEMTile",
    thumbnailSrc: "/images/gallery-thumbnails/GrowthSEMTile.png",

    usedOnPages: false,
  },
  {
    id: "gtmstack-hero",
    title: "Gtmstack Hero",
    componentPath: "@/components/animations/gtmstack-hero",
    thumbnailSrc: "/images/gallery-thumbnails/gtmstack-hero.png",

    usedOnPages: false,
  },
  {
    id: "health-care-tile",
    title: "Health Care Tile",
    componentPath: "@/components/animations/HealthCareTile",
    thumbnailSrc: "/images/gallery-thumbnails/HealthCareTile.png",

    usedOnPages: false,
  },
  {
    id: "higher-e-d-marketing-tile",
    title: "Higher E D Marketing Tile",
    componentPath: "@/components/animations/HigherEDMarketingTile",
    thumbnailSrc: "/images/gallery-thumbnails/HigherEDMarketingTile.png",

    usedOnPages: false,
  },
  {
    id: "impact-dashboard",
    title: "Impact Dashboard",
    componentPath: "@/components/animations/ImpactDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/ImpactDashboard.png",

    usedOnPages: false,
  },
  {
    id: "industrial-dashboard",
    title: "Industrial Dashboard",
    componentPath: "@/components/animations/IndustrialDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/IndustrialDashboard.png",

    usedOnPages: false,
  },
  {
    id: "industrial-m-f-g-tile",
    title: "Industrial MFG Tile",
    componentPath: "@/components/animations/Industrial-MFG-Tile",
    thumbnailSrc: "/images/gallery-thumbnails/Industrial-MFG-Tile.png",

    usedOnPages: false,
  },
  {
    id: "kpi-spotlight-mosaic",
    title: "Kpi Spotlight Mosaic",
    componentPath: "@/components/animations/KpiSpotlightMosaic",
    thumbnailSrc: "/images/gallery-thumbnails/KpiSpotlightMosaic.png",

    usedOnPages: false,
  },
  {
    id: "lead-gen-banner",
    title: "Lead Gen Banner",
    componentPath: "@/components/animations/LeadGenBanner",
    thumbnailSrc: "/images/gallery-thumbnails/LeadGenBanner.png",

    usedOnPages: false,
  },
  {
    id: "lead-gen-tile-animation",
    title: "Lead Gen Tile Animation",
    componentPath: "@/components/animations/LeadGenTileAnimation",
    thumbnailSrc: "/images/gallery-thumbnails/LeadGenTileAnimation.png",

    usedOnPages: false,
  },
  {
    id: "lifecycle-360",
    title: "Lifecycle 360",
    componentPath: "@/components/animations/Lifecycle-360",
    thumbnailSrc: "/images/gallery-thumbnails/Lifecycle-360.png",

    usedOnPages: false,
  },
  {
    id: "lifecycle-engine",
    title: "Lifecycle Engine",
    componentPath: "@/components/animations/LifecycleEngine",
    thumbnailSrc: "/images/gallery-thumbnails/LifecycleEngine.png",

    usedOnPages: false,
  },
  {
    id: "live-email-automation",
    title: "Live Email Automation",
    componentPath: "@/components/animations/Live-Email-Automation",
    thumbnailSrc: "/images/gallery-thumbnails/Live-Email-Automation.png",

    usedOnPages: false,
  },
  {
    id: "manufacturing-lifecycle-dashboard",
    title: "Manufacturing Lifecycledashboard",
    componentPath: "@/components/animations/Manufacturing-LifecycleDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/Manufacturing-LifecycleDashboard.png",

    usedOnPages: false,
  },
  {
    id: "manufacturing-lifecycle-dashboard (1)",
    title: "Manufacturing Lifecycledashboard (1)",
    componentPath: "@/components/animations/Manufacturing-LifecycleDashboard (1)",
    thumbnailSrc: "/images/gallery-thumbnails/Manufacturing-LifecycleDashboard (1).png",

    usedOnPages: false,
  },
  {
    id: "mar-tech-tile",
    title: "Mar Tech Tile",
    componentPath: "@/components/animations/MarTechTile",
    thumbnailSrc: "/images/gallery-thumbnails/MarTechTile.png",

    usedOnPages: false,
  },
  {
    id: "marketing-analytics-carousel",
    title: "Marketing Analytics Carousel",
    componentPath: "@/components/animations/Marketing-Analytics-Carousel",
    thumbnailSrc: "/images/gallery-thumbnails/Marketing-Analytics-Carousel.png",

    usedOnPages: false,
  },
  {
    id: "marketing-automation-live-feed",
    title: "Marketing Automation Live Feed",
    componentPath: "@/components/animations/Marketing-Automation-Live-Feed",
    thumbnailSrc: "/images/gallery-thumbnails/Marketing-Automation-Live-Feed.png",

    usedOnPages: false,
  },
  {
    id: "marketing-automation-live-feed (1)",
    title: "Marketing Automation Live Feed (1)",
    componentPath: "@/components/animations/Marketing-Automation-Live-Feed (1)",
    thumbnailSrc: "/images/gallery-thumbnails/Marketing-Automation-Live-Feed (1).png",

    usedOnPages: false,
  },
  {
    id: "marketing-funnel",
    title: "Marketing Funnel",
    componentPath: "@/components/animations/MarketingFunnel",
    thumbnailSrc: "/images/gallery-thumbnails/MarketingFunnel.png",

    usedOnPages: false,
  },
  {
    id: "marketing-operations-tile",
    title: "Marketing Operations Tile",
    componentPath: "@/components/animations/MarketingOperationsTile",
    thumbnailSrc: "/images/gallery-thumbnails/MarketingOperationsTile.png",

    usedOnPages: false,
  },
  {
    id: "n-g-o-s-d-o-tile",
    title: "N G O S D O Tile",
    componentPath: "@/components/animations/NGOSDOTile",
    thumbnailSrc: "/images/gallery-thumbnails/NGOSDOTile.png",

    usedOnPages: false,
  },
  {
    id: "n-g-o-tile",
    title: "N G O Tile",
    componentPath: "@/components/animations/NGOTile",
    thumbnailSrc: "/images/gallery-thumbnails/NGOTile.png",

    usedOnPages: false,
  },
  {
    id: "nexus-stakeholder-portal",
    title: "Nexus Stakeholder Portal",
    componentPath: "@/components/animations/NexusStakeholderPortal",
    thumbnailSrc: "/images/gallery-thumbnails/NexusStakeholderPortal.png",

    usedOnPages: false,
  },
  {
    id: "oil-gas-tile",
    title: "Oil Gas Tile",
    componentPath: "@/components/animations/OilGasTile",
    thumbnailSrc: "/images/gallery-thumbnails/OilGasTile.png",

    usedOnPages: false,
  },
  {
    id: "omni-analytics",
    title: "Omni Analytics",
    componentPath: "@/components/animations/Omni-Analytics",
    thumbnailSrc: "/images/gallery-thumbnails/Omni-Analytics.png",

    usedOnPages: false,
  },
  {
    id: "omni-retail-tile",
    title: "Omni Retail Tile",
    componentPath: "@/components/animations/OmniRetailTile",
    thumbnailSrc: "/images/gallery-thumbnails/OmniRetailTile.png",

    usedOnPages: false,
  },
  {
    id: "omnichannel-live-analytics",
    title: "Omnichannel Live Analytics",
    componentPath: "@/components/animations/OmnichannelLiveAnalytics",
    thumbnailSrc: "/images/gallery-thumbnails/OmnichannelLiveAnalytics.png",

    usedOnPages: false,
  },
  {
    id: "paid-advertising-hero",
    title: "Paid Advertising Hero",
    componentPath: "@/components/animations/PaidAdvertisingHero",
    thumbnailSrc: "/images/gallery-thumbnails/PaidAdvertisingHero.png",

    usedOnPages: false,
  },
  {
    id: "pipeline-dashboard",
    title: "Pipeline Dashboard",
    componentPath: "@/components/animations/PipelineDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/PipelineDashboard.png",

    usedOnPages: false,
  },
  {
    id: "plg-journey-dashboard",
    title: "Plg Journey Dashboard",
    componentPath: "@/components/animations/PlgJourneyDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/PlgJourneyDashboard.png",

    usedOnPages: false,
  },
  {
    id: "power-grid-dashboard",
    title: "Power Grid Dashboard",
    componentPath: "@/components/animations/PowerGridDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/PowerGridDashboard.png",

    usedOnPages: false,
  },
  {
    id: "pub-sec-tile",
    title: "Pub Sec Tile",
    componentPath: "@/components/animations/PubSecTile",
    thumbnailSrc: "/images/gallery-thumbnails/PubSecTile.png",

    usedOnPages: false,
  },
  {
    id: "quantum-dashboard",
    title: "Quantum Dashboard",
    componentPath: "@/components/animations/QuantumDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/QuantumDashboard.png",

    usedOnPages: false,
  },
  {
    id: "rev-ops-dash",
    title: "Rev Ops Dash",
    componentPath: "@/components/animations/RevOpsDash",
    thumbnailSrc: "/images/gallery-thumbnails/RevOpsDash.png",

    usedOnPages: false,
  },
  {
    id: "rev-ops-dashboard",
    title: "Rev Ops Dashboard",
    componentPath: "@/components/animations/RevOpsDashboard",
    thumbnailSrc: "/images/gallery-thumbnails/RevOpsDashboard.png",

    usedOnPages: false,
  },
  {
    id: "rev-ops-mesh-tile",
    title: "Rev Ops Mesh Tile",
    componentPath: "@/components/animations/RevOpsMeshTile",
    thumbnailSrc: "/images/gallery-thumbnails/RevOpsMeshTile.png",

    usedOnPages: false,
  },
  {
    id: "s-e-o-animation",
    title: "S E O Animation",
    componentPath: "@/components/animations/SEOAnimation",
    thumbnailSrc: "/images/gallery-thumbnails/SEOAnimation.png",

    usedOnPages: false,
  },
  {
    id: "s-e-o-hero",
    title: "S E O Hero",
    componentPath: "@/components/animations/SEOHero",
    thumbnailSrc: "/images/gallery-thumbnails/SEOHero.png",

    usedOnPages: false,
  },
  {
    id: "s-e-o-keyword-discovery",
    title: "S E O Keyword Discovery",
    componentPath: "@/components/animations/SEOKeywordDiscovery",
    thumbnailSrc: "/images/gallery-thumbnails/SEOKeywordDiscovery.png",

    usedOnPages: false,
  },
  {
    id: "sales-enablement-tile",
    title: "Sales Enablement Tile",
    componentPath: "@/components/animations/SalesEnablementTile",
    thumbnailSrc: "/images/gallery-thumbnails/SalesEnablementTile.png",

    usedOnPages: false,
  },
  {
    id: "scalability-radar",
    title: "Scalability Radar",
    componentPath: "@/components/animations/ScalabilityRadar",
    thumbnailSrc: "/images/gallery-thumbnails/ScalabilityRadar.png",

    usedOnPages: false,
  },
  {
    id: "s-e-o-growth-flow",
    title: "SEO Growthflow",
    componentPath: "@/components/animations/SEO-GrowthFlow",
    thumbnailSrc: "/images/gallery-thumbnails/SEO-GrowthFlow.png",

    usedOnPages: false,
  },
  {
    id: "social-media-hero",
    title: "Social Media Hero",
    componentPath: "@/components/animations/SocialMediaHero",
    thumbnailSrc: "/images/gallery-thumbnails/SocialMediaHero.png",

    usedOnPages: false,
  },
  {
    id: "strategy-insights-tile",
    title: "Strategy Insights Tile",
    componentPath: "@/components/animations/StrategyInsightsTile",
    thumbnailSrc: "/images/gallery-thumbnails/StrategyInsightsTile.png",

    usedOnPages: false,
  },
  {
    id: "systems-process-tile",
    title: "Systems Process Tile",
    componentPath: "@/components/animations/SystemsProcessTile",
    thumbnailSrc: "/images/gallery-thumbnails/SystemsProcessTile.png",

    usedOnPages: false,
  },
  {
    id: "telco-a-i-tile",
    title: "Telco A I Tile",
    componentPath: "@/components/animations/TelcoAITile",
    thumbnailSrc: "/images/gallery-thumbnails/TelcoAITile.png",

    usedOnPages: false,
  },
  {
    id: "telemetry-grid",
    title: "Telemetry Grid",
    componentPath: "@/components/animations/TelemetryGrid",
    thumbnailSrc: "/images/gallery-thumbnails/TelemetryGrid.png",

    usedOnPages: false,
  },
  {
    id: "video-creative-hero",
    title: "Video Creative Hero",
    componentPath: "@/components/animations/VideoCreativeHero",
    thumbnailSrc: "/images/gallery-thumbnails/VideoCreativeHero.png",

    usedOnPages: false,
  },
  {
    id: "video-marketing-analytics",
    title: "Video Marketing Analytics",
    componentPath: "@/components/animations/Video-Marketing-Analytics",
    thumbnailSrc: "/images/gallery-thumbnails/Video-Marketing-Analytics.png",

    usedOnPages: false,
  },
  {
    id: "video-marketing-analytics-tile",
    title: "Video Marketing Analytics Tile",
    componentPath: "@/components/animations/Video-Marketing-Analytics-Tile",
    thumbnailSrc: "/images/gallery-thumbnails/Video-Marketing-Analytics-Tile.png",

    usedOnPages: false,
  },
  {
    id: "waste-man",
    title: "Waste Man",
    componentPath: "@/components/animations/WasteMan",
    thumbnailSrc: "/images/gallery-thumbnails/WasteMan.png",

    usedOnPages: false,
  },
  {
    id: "wealth-manage-tile",
    title: "Wealth Manage Tile",
    componentPath: "@/components/animations/WealthManageTile",
    thumbnailSrc: "/images/gallery-thumbnails/WealthManageTile.png",

    usedOnPages: false,
  }
]
