/* AUTO-GENERATED. DO NOT EDIT BY HAND.
   Generated by scripts/generate-page-catalog.ts
*/
export const PAGE_CATALOG = [
  {
    "id": "home",
    "name": "Home",
    "route": "/",
    "kind": "top",
    "themeKey": "home",
    "accentHex": "#F59E0B",
    "accentName": "Gold (growth + impact)",
    "tone": "Visionary, confident, forward-moving; balanced hybrid.",
    "sections": [
      "Growth Impact (light surface, 4 bold metrics)",
      "The Growth Operating System (dark)",
      "Featured Case Studies (light)",
      "How We Work (dark)",
      "Strong CTA (light-to-blue gradient)"
    ]
  },
  {
    "id": "about",
    "name": "About",
    "route": "/about",
    "kind": "top",
    "themeKey": "about",
    "accentHex": "#2563EB",
    "accentName": "Blue (credibility)",
    "tone": "Credible, trusted, calm confidence; executive-ready.",
    "sections": [
      "Story & Credibility (light)",
      "Operating Philosophy (dark)",
      "Experience Timeline / Proof-of-Work (light)",
      "How We Work (dark)",
      "CTA to Connect (light)"
    ]
  },
  {
    "id": "expertise",
    "name": "Expertise (Landing)",
    "route": "/expertise",
    "kind": "top",
    "themeKey": "expertise",
    "accentHex": "#06B6D4",
    "accentName": "Cyan (system overview)",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "Four Pillar Grid (light)",
      "How the system fits together (dark)",
      "Featured proof (light)",
      "CTA (dark)"
    ]
  },
  {
    "id": "case-studies",
    "name": "Case Studies (Landing)",
    "route": "/case-studies",
    "kind": "top",
    "themeKey": "case-studies",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Impact Overview metrics (light)",
      "Case study grid (dark)",
      "Method summary (light)",
      "CTA (dark)"
    ]
  },
  {
    "id": "industries",
    "name": "Industries (Landing)",
    "route": "/industries",
    "kind": "top",
    "themeKey": "industries",
    "accentHex": "#2563EB",
    "accentName": "Neutral Blue (contextual)",
    "tone": "Contextual, adaptable, informed; still structured.",
    "sections": [
      "Industry grid (light)",
      "Common GTM friction patterns (dark)",
      "Cross-industry proof (light)",
      "CTA (dark)"
    ]
  },
  {
    "id": "expertise-account-based-marketing",
    "name": "Account-Based Marketing (ABM)",
    "route": "/expertise/account-based-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-account-based-marketing-abm",
    "name": "Account-Based Marketing (ABM)",
    "route": "/expertise/account-based-marketing-abm",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-attribution-and-measurement",
    "name": "Attribution & Measurement",
    "route": "/expertise/attribution-and-measurement",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-bi-data-engineering",
    "name": "BI & Data Engineering (GTM-Focused)",
    "route": "/expertise/bi-data-engineering",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-ai-in-marketing",
    "name": "AI in Marketing",
    "route": "/expertise/ai-in-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-content-marketing",
    "name": "Content Marketing",
    "route": "/expertise/content-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-content-strategy-systems",
    "name": "Content Strategy Systems",
    "route": "/expertise/content-strategy-systems",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-channel-partner-marketing",
    "name": "Channel Partner Marketing",
    "route": "/expertise/channel-partner-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-customer-experience",
    "name": "Customer Experience (CX)",
    "route": "/expertise/customer-experience",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-customer-experience-cx",
    "name": "Customer Experience (CX)",
    "route": "/expertise/customer-experience-cx",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-customer-marketing",
    "name": "Customer Marketing",
    "route": "/expertise/customer-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-data-governance",
    "name": "Data Governance",
    "route": "/expertise/data-governance",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-demand-generation",
    "name": "Demand Generation",
    "route": "/expertise/demand-generation",
    "kind": "topic",
    "themeKey": "topic-demand",
    "accentHex": "#F59E0B",
    "accentName": "Inherits Demand / Gold",
    "tone": "Performance + acceleration; pipeline and revenue outcomes.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-digital-marketing",
    "name": "Digital Marketing",
    "route": "/expertise/digital-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-email-marketing",
    "name": "Email Marketing & Nurture",
    "route": "/expertise/email-marketing",
    "kind": "topic",
    "themeKey": "topic-content",
    "accentHex": "#7C3AED",
    "accentName": "Inherits Content / Purple",
    "tone": "Narrative intelligence; scalable storytelling systems.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-event-marketing",
    "name": "Event Marketing & Webinars",
    "route": "/expertise/event-marketing",
    "kind": "topic",
    "themeKey": "topic-demand",
    "accentHex": "#F59E0B",
    "accentName": "Inherits Demand / Gold",
    "tone": "Performance + acceleration; pipeline and revenue outcomes.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-event-field-marketing",
    "name": "Event Marketing & Field Marketing",
    "route": "/expertise/event-field-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-growth-marketing",
    "name": "Growth Marketing",
    "route": "/expertise/growth-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-lifecycle-marketing",
    "name": "Lifecycle Marketing",
    "route": "/expertise/lifecycle-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-marketing-automation",
    "name": "Marketing Automation",
    "route": "/expertise/marketing-automation",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Inherits Systems / Cyan",
    "tone": "Technical precision; architecture, data, and integration clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-marketing-analytics-reporting",
    "name": "Marketing Analytics & Reporting",
    "route": "/expertise/marketing-analytics-reporting",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-marketing-operations",
    "name": "Marketing Operations",
    "route": "/expertise/marketing-operations",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-martech-optimization",
    "name": "MarTech Optimization",
    "route": "/expertise/martech-optimization",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-omnichannel-marketing",
    "name": "Omnichannel Marketing",
    "route": "/expertise/omnichannel-marketing",
    "kind": "topic",
    "themeKey": "topic-content",
    "accentHex": "#7C3AED",
    "accentName": "Inherits Content / Purple",
    "tone": "Narrative intelligence; scalable storytelling systems.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-paid-advertising",
    "name": "Paid Advertising",
    "route": "/expertise/paid-advertising",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-paid-advertising-sem",
    "name": "Paid Advertising & SEM",
    "route": "/expertise/paid-advertising-sem",
    "kind": "topic",
    "themeKey": "topic-demand",
    "accentHex": "#F59E0B",
    "accentName": "Inherits Demand / Gold",
    "tone": "Performance + acceleration; pipeline and revenue outcomes.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-product-marketing",
    "name": "Product Marketing",
    "route": "/expertise/product-marketing",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-revenue-operations",
    "name": "Revenue Operations (RevOps)",
    "route": "/expertise/revenue-operations",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-search-engine-optimization",
    "name": "Search Engine Optimization (SEO)",
    "route": "/expertise/search-engine-optimization",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-sales-enablement",
    "name": "Sales Enablement",
    "route": "/expertise/sales-enablement",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Inherits Systems / Cyan",
    "tone": "Technical precision; architecture, data, and integration clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-sales-enablement-alignment",
    "name": "Sales Enablement & Alignment",
    "route": "/expertise/sales-enablement-alignment",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-social-media",
    "name": "Social Media",
    "route": "/expertise/social-media",
    "kind": "topic",
    "themeKey": "topic-systems",
    "accentHex": "#06B6D4",
    "accentName": "Default (needs pillar override) / Cyan",
    "tone": "Systematic, structured, modern SaaS clarity.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-social-media-marketing",
    "name": "Social Media Marketing",
    "route": "/expertise/social-media-marketing",
    "kind": "topic",
    "themeKey": "topic-content",
    "accentHex": "#7C3AED",
    "accentName": "Inherits Content / Purple",
    "tone": "Narrative intelligence; scalable storytelling systems.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "expertise-video-marketing",
    "name": "Video Marketing & Webinars",
    "route": "/expertise/video-marketing",
    "kind": "topic",
    "themeKey": "topic-content",
    "accentHex": "#7C3AED",
    "accentName": "Inherits Content / Purple",
    "tone": "Narrative intelligence; scalable storytelling systems.",
    "sections": [
      "The Problem Pattern (light)",
      "The System Blueprint (dark)",
      "Implementation Model (light)",
      "Proof / Metrics (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-b2b-saas",
    "name": "Industry: B2B SaaS",
    "route": "/industries/b2b-saas",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-fintech",
    "name": "Industry: FinTech & Payments",
    "route": "/industries/fintech",
    "kind": "industry",
    "themeKey": "industry-financial",
    "accentHex": "#F59E0B",
    "accentName": "Financial / Restrained Gold",
    "tone": "Trust-first, risk-aware, executive-ready.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-financial-services",
    "name": "Industry: Financial Services",
    "route": "/industries/financial-services",
    "kind": "industry",
    "themeKey": "industry-financial",
    "accentHex": "#F59E0B",
    "accentName": "Financial / Restrained Gold",
    "tone": "Trust-first, risk-aware, executive-ready.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-healthcare",
    "name": "Industry: Healthcare",
    "route": "/industries/healthcare",
    "kind": "industry",
    "themeKey": "industry-healthcare",
    "accentHex": "#14B8A6",
    "accentName": "Healthcare / Soft Teal",
    "tone": "Trustworthy, calm, clean, human-centered.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-healthtech",
    "name": "Industry: HealthTech & Digital Health",
    "route": "/industries/healthtech",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-manufacturing",
    "name": "Industry: Manufacturing",
    "route": "/industries/manufacturing",
    "kind": "industry",
    "themeKey": "industry-manufacturing",
    "accentHex": "#F59E0B",
    "accentName": "Manufacturing / Industrial Amber",
    "tone": "Operational precision, structural efficiency, industrial strength.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-developer-tools",
    "name": "Industry: Developer Tools & DevOps",
    "route": "/industries/developer-tools",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-ecommerce",
    "name": "Industry: E-Commerce & Retail Tech",
    "route": "/industries/ecommerce",
    "kind": "industry",
    "themeKey": "industry-retail",
    "accentHex": "#F59E0B",
    "accentName": "Retail/Ecom / Performance Gold",
    "tone": "High-velocity, conversion-focused, still structured.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-energy-utilities",
    "name": "Industry: Energy & Utilities",
    "route": "/industries/energy-utilities",
    "kind": "industry",
    "themeKey": "industry-energy",
    "accentHex": "#14B8A6",
    "accentName": "Energy/Utilities / Teal",
    "tone": "Reliable, infrastructural, steady performance.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-public-sector-education",
    "name": "Industry: Public Sector & Education",
    "route": "/industries/public-sector-education",
    "kind": "industry",
    "themeKey": "industry-edu-nonprofit",
    "accentHex": "#6366F1",
    "accentName": "Education/Nonprofit / Indigo",
    "tone": "Balanced, mission-aware, optimistic professionalism.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-pubsec-government",
    "name": "Industry: Public Sector & Government",
    "route": "/industries/pubsec-government",
    "kind": "industry",
    "themeKey": "industry-public",
    "accentHex": "#2563EB",
    "accentName": "Public Sector / Blue",
    "tone": "Credible, clear, compliant, confident.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-retail-ecommerce",
    "name": "Industry: Retail & Ecommerce",
    "route": "/industries/retail-ecommerce",
    "kind": "industry",
    "themeKey": "industry-retail",
    "accentHex": "#F59E0B",
    "accentName": "Retail/Ecom / Performance Gold",
    "tone": "High-velocity, conversion-focused, still structured.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-supply-chain-logistics",
    "name": "Industry: Supply Chain & Logistics",
    "route": "/industries/supply-chain-logistics",
    "kind": "industry",
    "themeKey": "industry-manufacturing",
    "accentHex": "#F59E0B",
    "accentName": "Manufacturing / Industrial Amber",
    "tone": "Operational precision, structural efficiency, industrial strength.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-fleet-management-logistics",
    "name": "Industry: Fleet Management & Logistics",
    "route": "/industries/fleet-management-logistics",
    "kind": "industry",
    "themeKey": "industry-manufacturing",
    "accentHex": "#F59E0B",
    "accentName": "Manufacturing / Industrial Amber",
    "tone": "Operational precision, structural efficiency, industrial strength.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-cybersecurity",
    "name": "Industry: Cybersecurity",
    "route": "/industries/cybersecurity",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-climate-tech",
    "name": "Industry: Climate Tech & Sustainability",
    "route": "/industries/climate-tech",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-technology-saas",
    "name": "Industry: Technology & SaaS",
    "route": "/industries/technology-saas",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "industry-ai-ml",
    "name": "Industry: AI & Machine Learning",
    "route": "/industries/ai-ml",
    "kind": "industry",
    "themeKey": "industry-b2b-tech",
    "accentHex": "#06B6D4",
    "accentName": "B2B Tech / Cyan",
    "tone": "Technical, precise, modern SaaS clarity.",
    "sections": [
      "Industry Realities & Constraints (light)",
      "System Blueprint for this vertical (dark)",
      "Example Project / Proof (light)",
      "Playbook / Roadmap (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-abm-system-launch-prgx",
    "name": "Case Study: ABM System Launch",
    "route": "/case-studies/abm-system-launch-prgx",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-abm-journey-discrete-manufacturing-prgx",
    "name": "Case Study: Discrete Manufacturing ABM Journey",
    "route": "/case-studies/abm-journey-discrete-manufacturing-prgx",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-prgx-unified-revenue-operating-model",
    "name": "Case Study: 87% YoY Pipeline Growth via Unified ABM + RevOps Model",
    "route": "/case-studies/prgx-unified-revenue-operating-model",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-amcs-verticalized-abm-launch",
    "name": "Case Study: $1.2M Pipeline in 90 Days from Verticalized ABM",
    "route": "/case-studies/amcs-verticalized-abm-launch",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-end-to-end-abm-framework-amcs",
    "name": "Case Study: End-to-End ABM Framework",
    "route": "/case-studies/end-to-end-abm-framework-amcs",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-redhat-global-abm-activation",
    "name": "Case Study: 33% of Global Pipeline Influenced by ABM Activation",
    "route": "/case-studies/redhat-global-abm-activation",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-enterprise-abm-activation-red-hat",
    "name": "Case Study: Enterprise ABM Activation",
    "route": "/case-studies/enterprise-abm-activation-red-hat",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-salesforce-demandgen-analytics-platform",
    "name": "Case Study: Reporting Cycle Cut from 4 Days to 2 Hours",
    "route": "/case-studies/salesforce-demandgen-analytics-platform",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-revenue-analytics-dashboard-salesforce",
    "name": "Case Study: Revenue Analytics Dashboard",
    "route": "/case-studies/revenue-analytics-dashboard-salesforce",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-data-qa-integrity-pipeline-salesforce",
    "name": "Case Study: Data QA & Integrity Pipeline",
    "route": "/case-studies/data-qa-integrity-pipeline-salesforce",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-salesforce-fortune50-abm-events",
    "name": "Case Study: Fortune 50 ABM + Event Engine Driving Enterprise Pipeline",
    "route": "/case-studies/salesforce-fortune50-abm-events",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-singles-and-doubles-playbook-salesforce",
    "name": "Case Study: Singles & Doubles Playbook",
    "route": "/case-studies/singles-and-doubles-playbook-salesforce",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-sales-cloud-global-campaigns-salesforce",
    "name": "Case Study: Sales Cloud Global Campaigns",
    "route": "/case-studies/sales-cloud-global-campaigns-salesforce",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-getsatisfaction-growth-automation",
    "name": "Case Study: 164% YoY Traffic Growth + 43% QoQ Lead Lift",
    "route": "/case-studies/getsatisfaction-growth-automation",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-content-and-seo-infrastructure-crowd-factory-marketo",
    "name": "Case Study: Content & SEO Infrastructure",
    "route": "/case-studies/content-and-seo-infrastructure-crowd-factory-marketo",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-salemglobal-smb-seo-ppc-engine",
    "name": "Case Study: 500% YoY Client Growth via SMB SEO + PPC System",
    "route": "/case-studies/salemglobal-smb-seo-ppc-engine",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-event-to-store-lift-retail",
    "name": "Case Study: Event-to-Store Revenue Lift",
    "route": "/case-studies/event-to-store-lift-retail",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-marketing-flight-planner-ai-tool",
    "name": "Case Study: Marketing Flight Planner — AI GTM Maturity → Roadmap Engine",
    "route": "/case-studies/marketing-flight-planner-ai-tool",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  },
  {
    "id": "case-career-world-4d-interactive-resume",
    "name": "Case Study: Career World 4D — Interactive Resume Map",
    "route": "/case-studies/career-world-4d-interactive-resume",
    "kind": "case-study",
    "themeKey": "project",
    "accentHex": "#F59E0B",
    "accentName": "Gold (performance)",
    "tone": "Results-led, measurable, outcome-driven.",
    "sections": [
      "Problem (light)",
      "System Designed (dark)",
      "Implementation (light)",
      "Results (dark)",
      "CTA (light)"
    ]
  }
] as const;
export type PageCatalogItem = (typeof PAGE_CATALOG)[number];
