// Generated by scripts/gen-page-registry.ts — do not edit manually.
// Source of truth: src/data/page-registry.csv

export type TemplateId =
  | 'expertise.category'
  | 'expertise.topic'
  | 'expertise.main'
  | 'industry.base'
  | 'industries.main'
  | 'caseStudy.base'
  | 'home.base'
  | 'home.main'

export type Theme = 'dark' | 'light' | undefined

export interface PageRegistryRow {
  route: string
  fileRef: string
  pageTitle: string
  templateId: TemplateId
  contentKey: string
  theme: Theme
  heroVisualId: string
}

export const PAGE_REGISTRY: PageRegistryRow[] = [
  { route: "/", fileRef: "content/home.ts", pageTitle: "Home", templateId: 'home.main', contentKey: "home:main", theme: undefined, heroVisualId: "" },
  { route: "/expertise/demand-growth", fileRef: "content/expertise.ts", pageTitle: "Demand & Growth", templateId: 'expertise.category', contentKey: "pillar:demand-growth", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/demand-generation", fileRef: "content/expertise.ts", pageTitle: "Demand Generation", templateId: 'expertise.topic', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  { route: "/industries/healthcare", fileRef: "content/industries.ts", pageTitle: "Healthcare & Health Technology", templateId: 'industry.base', contentKey: "industry:healthcare", theme: 'light', heroVisualId: "" },
  { route: "/case-studies/event-to-store-lift-retail", fileRef: "content/case-studies.ts", pageTitle: "Event-to-Store Revenue Lift", templateId: 'caseStudy.base', contentKey: "project:event-to-store-lift-retail", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/content-engagement", fileRef: "content/expertise.ts", pageTitle: "Content & Engagement", templateId: 'expertise.category', contentKey: "pillar:content-engagement", theme: 'dark', heroVisualId: "" },
  { route: "/expertise", fileRef: "content/expertise/main.ts", pageTitle: "Expertise", templateId: 'expertise.main', contentKey: "expertise:main", theme: 'dark', heroVisualId: "" },
  { route: "/industries", fileRef: "content/industries/main.ts", pageTitle: "Industries", templateId: 'industries.main', contentKey: "industries:main", theme: 'dark', heroVisualId: "" }
]

export const PAGE_BY_ROUTE: Record<string, PageRegistryRow> = {
  "/": { route: "/", fileRef: "content/home.ts", pageTitle: "Home", templateId: 'home.main', contentKey: "home:main", theme: undefined, heroVisualId: "" },
  "/expertise/demand-growth": { route: "/expertise/demand-growth", fileRef: "content/expertise.ts", pageTitle: "Demand & Growth", templateId: 'expertise.category', contentKey: "pillar:demand-growth", theme: 'dark', heroVisualId: "" },
  "/expertise/demand-generation": { route: "/expertise/demand-generation", fileRef: "content/expertise.ts", pageTitle: "Demand Generation", templateId: 'expertise.topic', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  "/industries/healthcare": { route: "/industries/healthcare", fileRef: "content/industries.ts", pageTitle: "Healthcare & Health Technology", templateId: 'industry.base', contentKey: "industry:healthcare", theme: 'light', heroVisualId: "" },
  "/case-studies/event-to-store-lift-retail": { route: "/case-studies/event-to-store-lift-retail", fileRef: "content/case-studies.ts", pageTitle: "Event-to-Store Revenue Lift", templateId: 'caseStudy.base', contentKey: "project:event-to-store-lift-retail", theme: 'dark', heroVisualId: "" },
  "/expertise/content-engagement": { route: "/expertise/content-engagement", fileRef: "content/expertise.ts", pageTitle: "Content & Engagement", templateId: 'expertise.category', contentKey: "pillar:content-engagement", theme: 'dark', heroVisualId: "" },
  "/expertise": { route: "/expertise", fileRef: "content/expertise/main.ts", pageTitle: "Expertise", templateId: 'expertise.main', contentKey: "expertise:main", theme: 'dark', heroVisualId: "" },
  "/industries": { route: "/industries", fileRef: "content/industries/main.ts", pageTitle: "Industries", templateId: 'industries.main', contentKey: "industries:main", theme: 'dark', heroVisualId: "" }
}
