// Generated by scripts/gen-page-registry.ts — do not edit manually.
// Source of truth: src/data/page-registry.csv

// TemplateId union from legacy IDs; custom uploaded templates are free-form strings.
export type TemplateId =
  | 'expertise.category'
  | 'expertise.topic'
  | 'expertise.main'
  | 'gallery.main'
  | 'industry.base'
  | 'industries.main'
  | 'projects.main'
  | 'caseStudy.base'
  | 'home.base'
  | 'home.main'
  | (string & {})

export type Theme = 'dark' | 'light' | undefined

export interface PageRegistryRow {
  route: string
  fileRef: string
  pageTitle: string
  templateId: TemplateId
  contentKey: string
  theme: Theme
  heroVisualId: string
}

export const PAGE_REGISTRY: PageRegistryRow[] = [
  { route: "/", fileRef: "content/home.ts", pageTitle: "Home", templateId: 'home.stitch.main', contentKey: "home:stitch", theme: undefined, heroVisualId: "growth-ai-animation" },
  { route: "/about", fileRef: "content/about.ts", pageTitle: "About GTM Stack", templateId: 'about.main', contentKey: "about:main", theme: 'dark', heroVisualId: "gtmstack-hero-tile-v2" },
  { route: "/case-studies", fileRef: "content/case-studies.ts", pageTitle: "Case Studies", templateId: 'Uploaded_CaseStudies_v1', contentKey: "case-studies:main", theme: 'dark', heroVisualId: "gtm-strategy-audience-tile-v2" },
  { route: "/case-studies/event-to-store-lift-retail", fileRef: "content/case-studies.ts", pageTitle: "Event-to-Store Revenue Lift", templateId: 'caseStudy.base', contentKey: "case-studies:event-to-store-lift-retail", theme: 'dark', heroVisualId: "" },
  { route: "/contact", fileRef: "content/contact.ts", pageTitle: "Contact Us", templateId: 'home.main', contentKey: "contact:main", theme: 'light', heroVisualId: "" },
  { route: "/expertise", fileRef: "content/expertise/main.ts", pageTitle: "Expertise", templateId: 'Uploaded_Expertise_v1', contentKey: "expertise:stitch-main", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/account-based-marketing", fileRef: "content/expertise/account-based-marketing.ts", pageTitle: "Account-Based Marketing (ABM)", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:account-based-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/competitive-intel", fileRef: "content/expertise/competitive-intel.ts", pageTitle: "Competitive Intelligence & Positioning", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:competitive-intel", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/content-engagement", fileRef: "content/expertise/content-engagement.ts", pageTitle: "Content & Engagement", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "pillar:content-engagement", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/content-marketing", fileRef: "content/expertise/content-marketing.ts", pageTitle: "Content Creation & Personalization", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:content-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/crm-management", fileRef: "content/expertise/crm-management.ts", pageTitle: "CRM Management & Integration", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:crm-management", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/customer-marketing", fileRef: "content/expertise/customer-marketing.ts", pageTitle: "Customer Marketing & Journey Mapping", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:customer-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/demand-growth", fileRef: "content/expertise/demand-growth.ts", pageTitle: "Demand & Growth", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "pillar:demand-growth", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/demand-generation", fileRef: "content/expertise/demand-generation.ts", pageTitle: "Demand Generation Campaigns", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/digital-marketing", fileRef: "content/expertise/digital-marketing.ts", pageTitle: "Digital Marketing", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/event-marketing", fileRef: "content/expertise/event-marketing.ts", pageTitle: "Event & Tradeshow Management", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:event-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/strategy", fileRef: "content/expertise/strategy.ts", pageTitle: "GTM Strategy", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:gtm-strategy-development", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/lead-gen-scoring", fileRef: "content/expertise/lead-gen-scoring.ts", pageTitle: "Lead Generation & Scoring", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:lead-gen-scoring", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/marketing-analytics-reporting", fileRef: "content/expertise/marketing-analytics-reporting.ts", pageTitle: "Marketing Analytics & Reporting", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:marketing-analytics-reporting", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/marketing-automation", fileRef: "content/expertise/marketing-automation.ts", pageTitle: "Marketing Automation & Workflows", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:marketing-automation", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/paid-advertising-sem", fileRef: "content/expertise/paid-advertising-sem.ts", pageTitle: "Paid Media & Funnel Optimization", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:paid-advertising-sem", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/product-marketing", fileRef: "content/expertise/product-marketing.ts", pageTitle: "Product Marketing", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:product-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/analytics", fileRef: "content/expertise/analytics.ts", pageTitle: "Reporting Dashboards & Attribution", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:analytics", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/web-design-ui-ux", fileRef: "content/expertise/web-design-ui-ux.ts", pageTitle: "Responsive Web Design & UI/UX", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:web-design-ui-ux", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/roi-analysis", fileRef: "content/expertise/roi-analysis.ts", pageTitle: "ROI & Break-Even Analysis", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:roi-analysis", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/search-engine-optimization", fileRef: "content/expertise/search-engine-optimization.ts", pageTitle: "Search Engine Optimization & Management (SEO & SEM)", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:search-engine-optimization", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/social-media-marketing", fileRef: "content/expertise/social-media-marketing.ts", pageTitle: "Social Media & Reputation Management", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:social-media-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/strategy-insights", fileRef: "content/expertise/strategy-insights.ts", pageTitle: "Strategy & Insights", templateId: 'Uploaded_StratInsights_v1', contentKey: "pillar:strategy-insights", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/systems-operations", fileRef: "content/expertise/systems-operations.ts", pageTitle: "Systems & Operations", templateId: 'Uploaded_SystemOperations_v1', contentKey: "pillar:systems-operations", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/martech-optimization", fileRef: "content/expertise/martech-optimization.ts", pageTitle: "Tech Stack Optimization & Enablement", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:martech-optimization", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/sales-enablement", fileRef: "content/expertise/sales-enablement.ts", pageTitle: "Upsell/Cross-Sell Strategies", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:sales-enablement", theme: 'dark', heroVisualId: "" },
  { route: "/gallery", fileRef: "content/gallery/main.ts", pageTitle: "Animation Gallery", templateId: 'gallery.main', contentKey: "gallery:main", theme: 'dark', heroVisualId: "" },
  { route: "/industries", fileRef: "content/industries/main.ts", pageTitle: "Architecting Growth by Industry", templateId: 'industries.stitch.main', contentKey: "industries:main", theme: 'dark', heroVisualId: "" },
  { route: "/industries/cybersecurity", fileRef: "content/industries.ts", pageTitle: "Cybersecurity", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:cybersecurity", theme: 'dark', heroVisualId: "" },
  { route: "/industries/developer-tools", fileRef: "content/industries.ts", pageTitle: "Developer Tools & DevOps", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:developer-tools", theme: 'dark', heroVisualId: "" },
  { route: "/industries/energy-utilities", fileRef: "content/industries.ts", pageTitle: "Energy & Utilities", templateId: 'Uploaded_IndustrialIndustry_v1', contentKey: "industries:energy-utilities", theme: 'dark', heroVisualId: "" },
  { route: "/industries/financial-services", fileRef: "content/industries.ts", pageTitle: "Financial Services", templateId: 'Uploaded_Sector_v1', contentKey: "industries:financial-services", theme: 'light', heroVisualId: "" },
  { route: "/industries/fleet-management-logistics", fileRef: "content/industries.ts", pageTitle: "Fleet & Logistics", templateId: 'Uploaded_Sector_v1', contentKey: "industries:fleet-management-logistics", theme: 'dark', heroVisualId: "" },
  { route: "/industries/healthcare", fileRef: "content/industries.ts", pageTitle: "Healthcare & Health Technology", templateId: 'Uploaded_Healthcare_v1', contentKey: "industries:healthcare", theme: 'light', heroVisualId: "" },
  { route: "/industries/manufacturing", fileRef: "content/industries.ts", pageTitle: "Manufacturing", templateId: 'Uploaded_Sector_v1', contentKey: "industries:manufacturing", theme: 'dark', heroVisualId: "" },
  { route: "/industries/non-profit-education", fileRef: "content/industries.ts", pageTitle: "Non-Profit & Education", templateId: 'Uploaded_EDUtech_v1', contentKey: "industries:non-profit-education", theme: 'dark', heroVisualId: "" },
  { route: "/industries/pubsec-government", fileRef: "content/industries.ts", pageTitle: "Public Sector & Gov", templateId: 'Uploaded_Sector_v1', contentKey: "industries:pubsec-government", theme: 'dark', heroVisualId: "" },
  { route: "/industries/retail", fileRef: "content/industries.ts", pageTitle: "Retail & Consumer", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:retail", theme: 'dark', heroVisualId: "" },
  { route: "/industries/supply-chain-logistics", fileRef: "content/industries.ts", pageTitle: "Supply Chain & Logistics", templateId: 'Uploaded_IndustrialIndustry_v1', contentKey: "industries:supply-chain-logistics", theme: 'dark', heroVisualId: "" },
  { route: "/industries/technology-saas", fileRef: "content/industries.ts", pageTitle: "Technology & SaaS", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:technology-saas", theme: 'light', heroVisualId: "" },
  { route: "/p/test", fileRef: "content/home.ts", pageTitle: "Test CMS Page", templateId: 'home.main', contentKey: "home:main", theme: 'dark', heroVisualId: "" },
  { route: "/projects", fileRef: "content/projects/main.ts", pageTitle: "Projects", templateId: 'projects.main', contentKey: "projects:main", theme: 'dark', heroVisualId: "" },
  { route: "/resume", fileRef: "content/resume.ts", pageTitle: "Resume", templateId: 'profile.main', contentKey: "resume:main", theme: 'light', heroVisualId: "" }
]

export const PAGE_BY_ROUTE: Record<string, PageRegistryRow> = {
  "/": { route: "/", fileRef: "content/home.ts", pageTitle: "Home", templateId: 'home.stitch.main', contentKey: "home:stitch", theme: undefined, heroVisualId: "growth-ai-animation" },
  "/about": { route: "/about", fileRef: "content/about.ts", pageTitle: "About GTM Stack", templateId: 'about.main', contentKey: "about:main", theme: 'dark', heroVisualId: "gtmstack-hero-tile-v2" },
  "/case-studies": { route: "/case-studies", fileRef: "content/case-studies.ts", pageTitle: "Case Studies", templateId: 'Uploaded_CaseStudies_v1', contentKey: "case-studies:main", theme: 'dark', heroVisualId: "gtm-strategy-audience-tile-v2" },
  "/case-studies/event-to-store-lift-retail": { route: "/case-studies/event-to-store-lift-retail", fileRef: "content/case-studies.ts", pageTitle: "Event-to-Store Revenue Lift", templateId: 'caseStudy.base', contentKey: "case-studies:event-to-store-lift-retail", theme: 'dark', heroVisualId: "" },
  "/contact": { route: "/contact", fileRef: "content/contact.ts", pageTitle: "Contact Us", templateId: 'home.main', contentKey: "contact:main", theme: 'light', heroVisualId: "" },
  "/expertise": { route: "/expertise", fileRef: "content/expertise/main.ts", pageTitle: "Expertise", templateId: 'Uploaded_Expertise_v1', contentKey: "expertise:stitch-main", theme: 'dark', heroVisualId: "" },
  "/expertise/account-based-marketing": { route: "/expertise/account-based-marketing", fileRef: "content/expertise/account-based-marketing.ts", pageTitle: "Account-Based Marketing (ABM)", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:account-based-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/competitive-intel": { route: "/expertise/competitive-intel", fileRef: "content/expertise/competitive-intel.ts", pageTitle: "Competitive Intelligence & Positioning", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:competitive-intel", theme: 'dark', heroVisualId: "" },
  "/expertise/content-engagement": { route: "/expertise/content-engagement", fileRef: "content/expertise/content-engagement.ts", pageTitle: "Content & Engagement", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "pillar:content-engagement", theme: 'dark', heroVisualId: "" },
  "/expertise/content-marketing": { route: "/expertise/content-marketing", fileRef: "content/expertise/content-marketing.ts", pageTitle: "Content Creation & Personalization", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:content-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/crm-management": { route: "/expertise/crm-management", fileRef: "content/expertise/crm-management.ts", pageTitle: "CRM Management & Integration", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:crm-management", theme: 'dark', heroVisualId: "" },
  "/expertise/customer-marketing": { route: "/expertise/customer-marketing", fileRef: "content/expertise/customer-marketing.ts", pageTitle: "Customer Marketing & Journey Mapping", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:customer-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/demand-growth": { route: "/expertise/demand-growth", fileRef: "content/expertise/demand-growth.ts", pageTitle: "Demand & Growth", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "pillar:demand-growth", theme: 'dark', heroVisualId: "" },
  "/expertise/demand-generation": { route: "/expertise/demand-generation", fileRef: "content/expertise/demand-generation.ts", pageTitle: "Demand Generation Campaigns", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  "/expertise/digital-marketing": { route: "/expertise/digital-marketing", fileRef: "content/expertise/digital-marketing.ts", pageTitle: "Digital Marketing", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/event-marketing": { route: "/expertise/event-marketing", fileRef: "content/expertise/event-marketing.ts", pageTitle: "Event & Tradeshow Management", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:event-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/strategy": { route: "/expertise/strategy", fileRef: "content/expertise/strategy.ts", pageTitle: "GTM Strategy", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:gtm-strategy-development", theme: 'dark', heroVisualId: "" },
  "/expertise/lead-gen-scoring": { route: "/expertise/lead-gen-scoring", fileRef: "content/expertise/lead-gen-scoring.ts", pageTitle: "Lead Generation & Scoring", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:lead-gen-scoring", theme: 'dark', heroVisualId: "" },
  "/expertise/marketing-analytics-reporting": { route: "/expertise/marketing-analytics-reporting", fileRef: "content/expertise/marketing-analytics-reporting.ts", pageTitle: "Marketing Analytics & Reporting", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:marketing-analytics-reporting", theme: 'dark', heroVisualId: "" },
  "/expertise/marketing-automation": { route: "/expertise/marketing-automation", fileRef: "content/expertise/marketing-automation.ts", pageTitle: "Marketing Automation & Workflows", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:marketing-automation", theme: 'dark', heroVisualId: "" },
  "/expertise/paid-advertising-sem": { route: "/expertise/paid-advertising-sem", fileRef: "content/expertise/paid-advertising-sem.ts", pageTitle: "Paid Media & Funnel Optimization", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:paid-advertising-sem", theme: 'dark', heroVisualId: "" },
  "/expertise/product-marketing": { route: "/expertise/product-marketing", fileRef: "content/expertise/product-marketing.ts", pageTitle: "Product Marketing", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:product-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/analytics": { route: "/expertise/analytics", fileRef: "content/expertise/analytics.ts", pageTitle: "Reporting Dashboards & Attribution", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:analytics", theme: 'dark', heroVisualId: "" },
  "/expertise/web-design-ui-ux": { route: "/expertise/web-design-ui-ux", fileRef: "content/expertise/web-design-ui-ux.ts", pageTitle: "Responsive Web Design & UI/UX", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:web-design-ui-ux", theme: 'dark', heroVisualId: "" },
  "/expertise/roi-analysis": { route: "/expertise/roi-analysis", fileRef: "content/expertise/roi-analysis.ts", pageTitle: "ROI & Break-Even Analysis", templateId: 'Uploaded_StratInsights_v1', contentKey: "expertise:roi-analysis", theme: 'dark', heroVisualId: "" },
  "/expertise/search-engine-optimization": { route: "/expertise/search-engine-optimization", fileRef: "content/expertise/search-engine-optimization.ts", pageTitle: "Search Engine Optimization & Management (SEO & SEM)", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:search-engine-optimization", theme: 'dark', heroVisualId: "" },
  "/expertise/social-media-marketing": { route: "/expertise/social-media-marketing", fileRef: "content/expertise/social-media-marketing.ts", pageTitle: "Social Media & Reputation Management", templateId: 'Uploaded_ContentEngagement_v1', contentKey: "expertise:social-media-marketing", theme: 'dark', heroVisualId: "" },
  "/expertise/strategy-insights": { route: "/expertise/strategy-insights", fileRef: "content/expertise/strategy-insights.ts", pageTitle: "Strategy & Insights", templateId: 'Uploaded_StratInsights_v1', contentKey: "pillar:strategy-insights", theme: 'dark', heroVisualId: "" },
  "/expertise/systems-operations": { route: "/expertise/systems-operations", fileRef: "content/expertise/systems-operations.ts", pageTitle: "Systems & Operations", templateId: 'Uploaded_SystemOperations_v1', contentKey: "pillar:systems-operations", theme: 'dark', heroVisualId: "" },
  "/expertise/martech-optimization": { route: "/expertise/martech-optimization", fileRef: "content/expertise/martech-optimization.ts", pageTitle: "Tech Stack Optimization & Enablement", templateId: 'Uploaded_SystemOperations_v1', contentKey: "expertise:martech-optimization", theme: 'dark', heroVisualId: "" },
  "/expertise/sales-enablement": { route: "/expertise/sales-enablement", fileRef: "content/expertise/sales-enablement.ts", pageTitle: "Upsell/Cross-Sell Strategies", templateId: 'Uploaded_DemandGrowth_v1', contentKey: "expertise:sales-enablement", theme: 'dark', heroVisualId: "" },
  "/gallery": { route: "/gallery", fileRef: "content/gallery/main.ts", pageTitle: "Animation Gallery", templateId: 'gallery.main', contentKey: "gallery:main", theme: 'dark', heroVisualId: "" },
  "/industries": { route: "/industries", fileRef: "content/industries/main.ts", pageTitle: "Architecting Growth by Industry", templateId: 'industries.stitch.main', contentKey: "industries:main", theme: 'dark', heroVisualId: "" },
  "/industries/cybersecurity": { route: "/industries/cybersecurity", fileRef: "content/industries.ts", pageTitle: "Cybersecurity", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:cybersecurity", theme: 'dark', heroVisualId: "" },
  "/industries/developer-tools": { route: "/industries/developer-tools", fileRef: "content/industries.ts", pageTitle: "Developer Tools & DevOps", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:developer-tools", theme: 'dark', heroVisualId: "" },
  "/industries/energy-utilities": { route: "/industries/energy-utilities", fileRef: "content/industries.ts", pageTitle: "Energy & Utilities", templateId: 'Uploaded_IndustrialIndustry_v1', contentKey: "industries:energy-utilities", theme: 'dark', heroVisualId: "" },
  "/industries/financial-services": { route: "/industries/financial-services", fileRef: "content/industries.ts", pageTitle: "Financial Services", templateId: 'Uploaded_Sector_v1', contentKey: "industries:financial-services", theme: 'light', heroVisualId: "" },
  "/industries/fleet-management-logistics": { route: "/industries/fleet-management-logistics", fileRef: "content/industries.ts", pageTitle: "Fleet & Logistics", templateId: 'Uploaded_Sector_v1', contentKey: "industries:fleet-management-logistics", theme: 'dark', heroVisualId: "" },
  "/industries/healthcare": { route: "/industries/healthcare", fileRef: "content/industries.ts", pageTitle: "Healthcare & Health Technology", templateId: 'Uploaded_Healthcare_v1', contentKey: "industries:healthcare", theme: 'light', heroVisualId: "" },
  "/industries/manufacturing": { route: "/industries/manufacturing", fileRef: "content/industries.ts", pageTitle: "Manufacturing", templateId: 'Uploaded_Sector_v1', contentKey: "industries:manufacturing", theme: 'dark', heroVisualId: "" },
  "/industries/non-profit-education": { route: "/industries/non-profit-education", fileRef: "content/industries.ts", pageTitle: "Non-Profit & Education", templateId: 'Uploaded_EDUtech_v1', contentKey: "industries:non-profit-education", theme: 'dark', heroVisualId: "" },
  "/industries/pubsec-government": { route: "/industries/pubsec-government", fileRef: "content/industries.ts", pageTitle: "Public Sector & Gov", templateId: 'Uploaded_Sector_v1', contentKey: "industries:pubsec-government", theme: 'dark', heroVisualId: "" },
  "/industries/retail": { route: "/industries/retail", fileRef: "content/industries.ts", pageTitle: "Retail & Consumer", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:retail", theme: 'dark', heroVisualId: "" },
  "/industries/supply-chain-logistics": { route: "/industries/supply-chain-logistics", fileRef: "content/industries.ts", pageTitle: "Supply Chain & Logistics", templateId: 'Uploaded_IndustrialIndustry_v1', contentKey: "industries:supply-chain-logistics", theme: 'dark', heroVisualId: "" },
  "/industries/technology-saas": { route: "/industries/technology-saas", fileRef: "content/industries.ts", pageTitle: "Technology & SaaS", templateId: 'Uploaded_B2BTechIndustry_v1', contentKey: "industries:technology-saas", theme: 'light', heroVisualId: "" },
  "/p/test": { route: "/p/test", fileRef: "content/home.ts", pageTitle: "Test CMS Page", templateId: 'home.main', contentKey: "home:main", theme: 'dark', heroVisualId: "" },
  "/projects": { route: "/projects", fileRef: "content/projects/main.ts", pageTitle: "Projects", templateId: 'projects.main', contentKey: "projects:main", theme: 'dark', heroVisualId: "" },
  "/resume": { route: "/resume", fileRef: "content/resume.ts", pageTitle: "Resume", templateId: 'profile.main', contentKey: "resume:main", theme: 'light', heroVisualId: "" }
}
