// Generated by scripts/gen-page-registry.ts — do not edit manually.
// Source of truth: src/data/page-registry.csv

// TemplateId union from legacy IDs; custom uploaded templates are free-form strings.
export type TemplateId =
  | 'expertise.category'
  | 'expertise.topic'
  | 'expertise.main'
  | 'gallery.main'
  | 'industry.base'
  | 'industries.main'
  | 'projects.main'
  | 'caseStudy.base'
  | 'home.base'
  | 'home.main'
  | (string & {})

export type Theme = 'dark' | 'light' | undefined

export interface PageRegistryRow {
  route: string
  fileRef: string
  pageTitle: string
  templateId: TemplateId
  contentKey: string
  theme: Theme
  heroVisualId: string
}

export const PAGE_REGISTRY: PageRegistryRow[] = [
  { route: "/", fileRef: "content/home.ts", pageTitle: "Home", templateId: 'home.main', contentKey: "home:main", theme: undefined, heroVisualId: "" },
  { route: "/expertise/demand-growth", fileRef: "content/expertise.ts", pageTitle: "Demand & Growth", templateId: 'Uploaded_Expertise_DemandGrowth_v1', contentKey: "pillar:demand-growth", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/demand-generation", fileRef: "content/expertise.ts", pageTitle: "Demand Generation", templateId: 'expertise.category', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  { route: "/industries/healthcare", fileRef: "content/industries.ts", pageTitle: "Healthcare & Health Technology", templateId: 'industry.base', contentKey: "industries:healthcare", theme: 'light', heroVisualId: "" },
  { route: "/case-studies/event-to-store-lift-retail", fileRef: "content/case-studies.ts", pageTitle: "Event-to-Store Revenue Lift", templateId: 'caseStudy.base', contentKey: "case-studies:event-to-store-lift-retail", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/content-engagement", fileRef: "content/expertise.ts", pageTitle: "Content & Engagement", templateId: 'Uploaded_Expertise_ContentEngagement_v1', contentKey: "default:content", theme: 'dark', heroVisualId: "" },
  { route: "/expertise", fileRef: "content/expertise/main.ts", pageTitle: "Expertise", templateId: 'expertise.main', contentKey: "expertise:main", theme: 'dark', heroVisualId: "" },
  { route: "/industries", fileRef: "content/industries/main.ts", pageTitle: "Industries", templateId: 'industries.main', contentKey: "industries:main", theme: 'dark', heroVisualId: "" },
  { route: "/gallery", fileRef: "content/gallery/main.ts", pageTitle: "Animation Gallery", templateId: 'gallery.main', contentKey: "gallery:main", theme: 'dark', heroVisualId: "" },
  { route: "/p/test", fileRef: "content/home.ts", pageTitle: "Test CMS Page", templateId: 'home.main', contentKey: "home:main", theme: 'dark', heroVisualId: "" },
  { route: "/about", fileRef: "content/about.ts", pageTitle: "About GTM Stack", templateId: 'home.main', contentKey: "about:main", theme: 'dark', heroVisualId: "" },
  { route: "/contact", fileRef: "content/contact.ts", pageTitle: "Contact Us", templateId: 'home.main', contentKey: "contact:main", theme: 'light', heroVisualId: "" },
  { route: "/resume", fileRef: "content/resume.ts", pageTitle: "Resume", templateId: 'home.main', contentKey: "resume:main", theme: 'light', heroVisualId: "" },
  { route: "/projects", fileRef: "content/projects/main.ts", pageTitle: "Projects", templateId: 'projects.main', contentKey: "projects:main", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/analytics", fileRef: "content/expertise.ts", pageTitle: "Analytics & Insights", templateId: 'expertise.topic', contentKey: "expertise:marketing-analytics-reporting", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/automation", fileRef: "content/expertise.ts", pageTitle: "Marketing Automation", templateId: 'expertise.topic', contentKey: "expertise:marketing-automation", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/optimization", fileRef: "content/expertise.ts", pageTitle: "Revenue Optimization", templateId: 'expertise.topic', contentKey: "expertise:revenue-operations", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/strategy", fileRef: "content/expertise.ts", pageTitle: "GTM Strategy", templateId: 'expertise.topic', contentKey: "expertise:gtm-strategy-development", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/strategy-insights", fileRef: "content/expertise.ts", pageTitle: "Strategy & Insights", templateId: 'expertise.category', contentKey: "pillar:strategy-insights", theme: 'dark', heroVisualId: "" },
  { route: "/expertise/systems-operations", fileRef: "content/expertise.ts", pageTitle: "Systems & Operations", templateId: 'expertise.category', contentKey: "pillar:systems-operations", theme: 'dark', heroVisualId: "" },
  { route: "/industries/b2b-saas", fileRef: "content/industries.ts", pageTitle: "B2B SaaS", templateId: 'industry.base', contentKey: "industries:b2b-saas", theme: 'light', heroVisualId: "" },
  { route: "/industries/financial-services", fileRef: "content/industries.ts", pageTitle: "Financial Services", templateId: 'industry.base', contentKey: "industries:financial-services", theme: 'light', heroVisualId: "" },
  { route: "/services/demand-generation", fileRef: "content/expertise.ts", pageTitle: "Demand Generation", templateId: 'expertise.topic', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  { route: "/industries/manufacturing", fileRef: "content/industries.ts", pageTitle: "Manufacturing", templateId: 'industry.base', contentKey: "industries:manufacturing", theme: 'dark', heroVisualId: "" },
  { route: "/industries/retail", fileRef: "content/industries.ts", pageTitle: "Retail & Consumer", templateId: 'industry.base', contentKey: "industries:retail", theme: 'dark', heroVisualId: "" },
  { route: "/industries/fleet-management-logistics", fileRef: "content/industries.ts", pageTitle: "Fleet & Logistics", templateId: 'industry.base', contentKey: "industries:fleet-management-logistics", theme: 'dark', heroVisualId: "" },
  { route: "/industries/pubsec-government", fileRef: "content/industries.ts", pageTitle: "Public Sector & Gov", templateId: 'industry.base', contentKey: "industries:pubsec-government", theme: 'dark', heroVisualId: "" },
  { route: "/services/content-marketing", fileRef: "content/expertise.ts", pageTitle: "Content Marketing", templateId: 'expertise.topic', contentKey: "expertise:content-engagement", theme: 'dark', heroVisualId: "" },
  { route: "/services/paid-advertising", fileRef: "content/expertise.ts", pageTitle: "Paid Advertising", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/services/seo", fileRef: "content/expertise.ts", pageTitle: "SEO & Organic", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/services/social-media", fileRef: "content/expertise.ts", pageTitle: "Social Media", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/services/video-creative", fileRef: "content/expertise.ts", pageTitle: "Video & Creative", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  { route: "/case-studies", fileRef: "content/case-studies.ts", pageTitle: "Case Studies", templateId: 'home.main', contentKey: "home:main", theme: 'dark', heroVisualId: "" }
]

export const PAGE_BY_ROUTE: Record<string, PageRegistryRow> = {
  "/": { route: "/", fileRef: "content/home.ts", pageTitle: "Home", templateId: 'home.main', contentKey: "home:main", theme: undefined, heroVisualId: "" },
  "/expertise/demand-growth": { route: "/expertise/demand-growth", fileRef: "content/expertise.ts", pageTitle: "Demand & Growth", templateId: 'Uploaded_Expertise_DemandGrowth_v1', contentKey: "pillar:demand-growth", theme: 'dark', heroVisualId: "" },
  "/expertise/demand-generation": { route: "/expertise/demand-generation", fileRef: "content/expertise.ts", pageTitle: "Demand Generation", templateId: 'expertise.category', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  "/industries/healthcare": { route: "/industries/healthcare", fileRef: "content/industries.ts", pageTitle: "Healthcare & Health Technology", templateId: 'industry.base', contentKey: "industries:healthcare", theme: 'light', heroVisualId: "" },
  "/case-studies/event-to-store-lift-retail": { route: "/case-studies/event-to-store-lift-retail", fileRef: "content/case-studies.ts", pageTitle: "Event-to-Store Revenue Lift", templateId: 'caseStudy.base', contentKey: "case-studies:event-to-store-lift-retail", theme: 'dark', heroVisualId: "" },
  "/expertise/content-engagement": { route: "/expertise/content-engagement", fileRef: "content/expertise.ts", pageTitle: "Content & Engagement", templateId: 'Uploaded_Expertise_ContentEngagement_v1', contentKey: "default:content", theme: 'dark', heroVisualId: "" },
  "/expertise": { route: "/expertise", fileRef: "content/expertise/main.ts", pageTitle: "Expertise", templateId: 'expertise.main', contentKey: "expertise:main", theme: 'dark', heroVisualId: "" },
  "/industries": { route: "/industries", fileRef: "content/industries/main.ts", pageTitle: "Industries", templateId: 'industries.main', contentKey: "industries:main", theme: 'dark', heroVisualId: "" },
  "/gallery": { route: "/gallery", fileRef: "content/gallery/main.ts", pageTitle: "Animation Gallery", templateId: 'gallery.main', contentKey: "gallery:main", theme: 'dark', heroVisualId: "" },
  "/p/test": { route: "/p/test", fileRef: "content/home.ts", pageTitle: "Test CMS Page", templateId: 'home.main', contentKey: "home:main", theme: 'dark', heroVisualId: "" },
  "/about": { route: "/about", fileRef: "content/about.ts", pageTitle: "About GTM Stack", templateId: 'home.main', contentKey: "about:main", theme: 'dark', heroVisualId: "" },
  "/contact": { route: "/contact", fileRef: "content/contact.ts", pageTitle: "Contact Us", templateId: 'home.main', contentKey: "contact:main", theme: 'light', heroVisualId: "" },
  "/resume": { route: "/resume", fileRef: "content/resume.ts", pageTitle: "Resume", templateId: 'home.main', contentKey: "resume:main", theme: 'light', heroVisualId: "" },
  "/projects": { route: "/projects", fileRef: "content/projects/main.ts", pageTitle: "Projects", templateId: 'projects.main', contentKey: "projects:main", theme: 'dark', heroVisualId: "" },
  "/expertise/analytics": { route: "/expertise/analytics", fileRef: "content/expertise.ts", pageTitle: "Analytics & Insights", templateId: 'expertise.topic', contentKey: "expertise:marketing-analytics-reporting", theme: 'dark', heroVisualId: "" },
  "/expertise/automation": { route: "/expertise/automation", fileRef: "content/expertise.ts", pageTitle: "Marketing Automation", templateId: 'expertise.topic', contentKey: "expertise:marketing-automation", theme: 'dark', heroVisualId: "" },
  "/expertise/optimization": { route: "/expertise/optimization", fileRef: "content/expertise.ts", pageTitle: "Revenue Optimization", templateId: 'expertise.topic', contentKey: "expertise:revenue-operations", theme: 'dark', heroVisualId: "" },
  "/expertise/strategy": { route: "/expertise/strategy", fileRef: "content/expertise.ts", pageTitle: "GTM Strategy", templateId: 'expertise.topic', contentKey: "expertise:gtm-strategy-development", theme: 'dark', heroVisualId: "" },
  "/expertise/strategy-insights": { route: "/expertise/strategy-insights", fileRef: "content/expertise.ts", pageTitle: "Strategy & Insights", templateId: 'expertise.category', contentKey: "pillar:strategy-insights", theme: 'dark', heroVisualId: "" },
  "/expertise/systems-operations": { route: "/expertise/systems-operations", fileRef: "content/expertise.ts", pageTitle: "Systems & Operations", templateId: 'expertise.category', contentKey: "pillar:systems-operations", theme: 'dark', heroVisualId: "" },
  "/industries/b2b-saas": { route: "/industries/b2b-saas", fileRef: "content/industries.ts", pageTitle: "B2B SaaS", templateId: 'industry.base', contentKey: "industries:b2b-saas", theme: 'light', heroVisualId: "" },
  "/industries/financial-services": { route: "/industries/financial-services", fileRef: "content/industries.ts", pageTitle: "Financial Services", templateId: 'industry.base', contentKey: "industries:financial-services", theme: 'light', heroVisualId: "" },
  "/services/demand-generation": { route: "/services/demand-generation", fileRef: "content/expertise.ts", pageTitle: "Demand Generation", templateId: 'expertise.topic', contentKey: "expertise:demand-generation", theme: 'dark', heroVisualId: "" },
  "/industries/manufacturing": { route: "/industries/manufacturing", fileRef: "content/industries.ts", pageTitle: "Manufacturing", templateId: 'industry.base', contentKey: "industries:manufacturing", theme: 'dark', heroVisualId: "" },
  "/industries/retail": { route: "/industries/retail", fileRef: "content/industries.ts", pageTitle: "Retail & Consumer", templateId: 'industry.base', contentKey: "industries:retail", theme: 'dark', heroVisualId: "" },
  "/industries/fleet-management-logistics": { route: "/industries/fleet-management-logistics", fileRef: "content/industries.ts", pageTitle: "Fleet & Logistics", templateId: 'industry.base', contentKey: "industries:fleet-management-logistics", theme: 'dark', heroVisualId: "" },
  "/industries/pubsec-government": { route: "/industries/pubsec-government", fileRef: "content/industries.ts", pageTitle: "Public Sector & Gov", templateId: 'industry.base', contentKey: "industries:pubsec-government", theme: 'dark', heroVisualId: "" },
  "/services/content-marketing": { route: "/services/content-marketing", fileRef: "content/expertise.ts", pageTitle: "Content Marketing", templateId: 'expertise.topic', contentKey: "expertise:content-engagement", theme: 'dark', heroVisualId: "" },
  "/services/paid-advertising": { route: "/services/paid-advertising", fileRef: "content/expertise.ts", pageTitle: "Paid Advertising", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  "/services/seo": { route: "/services/seo", fileRef: "content/expertise.ts", pageTitle: "SEO & Organic", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  "/services/social-media": { route: "/services/social-media", fileRef: "content/expertise.ts", pageTitle: "Social Media", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  "/services/video-creative": { route: "/services/video-creative", fileRef: "content/expertise.ts", pageTitle: "Video & Creative", templateId: 'expertise.topic', contentKey: "expertise:digital-marketing", theme: 'dark', heroVisualId: "" },
  "/case-studies": { route: "/case-studies", fileRef: "content/case-studies.ts", pageTitle: "Case Studies", templateId: 'home.main', contentKey: "home:main", theme: 'dark', heroVisualId: "" }
}
